/* Deutsch Trainer — extended vocabulary pack (merged with dedup in index.html) */
window.EXTRA_VOCAB={nouns:[],verbs:[],adjs:[],phrases:[],imgs:{},pics:[]};

/* ===== time & calendar ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Montag',en:'Monday',g:'m',pl:'Montage'},{de:'Dienstag',en:'Tuesday',g:'m',pl:'Dienstage'},
 {de:'Mittwoch',en:'Wednesday',g:'m',pl:'Mittwoche'},{de:'Donnerstag',en:'Thursday',g:'m',pl:'Donnerstage'},
 {de:'Freitag',en:'Friday',g:'m',pl:'Freitage'},{de:'Samstag',en:'Saturday',g:'m',pl:'Samstage'},
 {de:'Sonntag',en:'Sunday',g:'m',pl:'Sonntage'},{de:'Wochenende',en:'weekend',g:'n',pl:'Wochenenden'},
 {de:'Januar',en:'January',g:'m',pl:null},{de:'Februar',en:'February',g:'m',pl:null},
 {de:'März',en:'March',g:'m',pl:null},{de:'April',en:'April',g:'m',pl:null},
 {de:'Mai',en:'May',g:'m',pl:null},{de:'Juni',en:'June',g:'m',pl:null},
 {de:'Juli',en:'July',g:'m',pl:null},{de:'August',en:'August',g:'m',pl:null},
 {de:'September',en:'September',g:'m',pl:null},{de:'Oktober',en:'October',g:'m',pl:null},
 {de:'November',en:'November',g:'m',pl:null},{de:'Dezember',en:'December',g:'m',pl:null},
 {de:'Frühling',en:'spring',g:'m',pl:'Frühlinge'},{de:'Sommer',en:'summer',g:'m',pl:'Sommer'},
 {de:'Herbst',en:'autumn',g:'m',pl:'Herbste'},{de:'Winter',en:'winter',g:'m',pl:'Winter'},
 {de:'Stunde',en:'hour',g:'f',pl:'Stunden'},{de:'Minute',en:'minute',g:'f',pl:'Minuten'},
 {de:'Sekunde',en:'second',g:'f',pl:'Sekunden'},{de:'Moment',en:'moment',g:'m',pl:'Momente'},
 {de:'Morgen',en:'morning',g:'m',pl:'Morgen'},{de:'Mittag',en:'noon',g:'m',pl:'Mittage'},
 {de:'Nachmittag',en:'afternoon',g:'m',pl:'Nachmittage'},{de:'Abend',en:'evening',g:'m',pl:'Abende'},
 {de:'Feiertag',en:'public holiday',g:'m',pl:'Feiertage'},{de:'Geburtstag',en:'birthday',g:'m',pl:'Geburtstage'},
 {de:'Jahrhundert',en:'century',g:'n',pl:'Jahrhunderte'},{de:'Jahreszeit',en:'season',g:'f',pl:'Jahreszeiten'},
 {de:'Datum',en:'date',g:'n',pl:'Daten'},{de:'Kalender',en:'calendar',g:'m',pl:'Kalender'},
 {de:'Wecker',en:'alarm clock',g:'m',pl:'Wecker'},{de:'Zukunft',en:'future',g:'f',pl:null},
 {de:'Vergangenheit',en:'past',g:'f',pl:null},{de:'Gegenwart',en:'present (time)',g:'f',pl:null},
 {de:'Anfang',en:'beginning',g:'m',pl:'Anfänge'},{de:'Ende',en:'end',g:'n',pl:'Enden'},
 {de:'Pause',en:'break',g:'f',pl:'Pausen'},{de:'Termin',en:'appointment',g:'m',pl:'Termine'}
);

/* ===== family & people ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Familie',en:'family',g:'f',pl:'Familien'},{de:'Sohn',en:'son',g:'m',pl:'Söhne'},
 {de:'Tochter',en:'daughter',g:'f',pl:'Töchter'},{de:'Enkel',en:'grandson',g:'m',pl:'Enkel'},
 {de:'Enkelin',en:'granddaughter',g:'f',pl:'Enkelinnen'},{de:'Cousin',en:'male cousin',g:'m',pl:'Cousins'},
 {de:'Cousine',en:'female cousin',g:'f',pl:'Cousinen'},{de:'Ehemann',en:'husband',g:'m',pl:'Ehemänner'},
 {de:'Ehefrau',en:'wife',g:'f',pl:'Ehefrauen'},{de:'Partner',en:'partner',g:'m',pl:'Partner'},
 {de:'Partnerin',en:'female partner',g:'f',pl:'Partnerinnen'},{de:'Freundin',en:'female friend / girlfriend',g:'f',pl:'Freundinnen'},
 {de:'Junge',en:'boy',g:'m',pl:'Jungen'},{de:'Person',en:'person',g:'f',pl:'Personen'},
 {de:'Mensch',en:'human being',g:'m',pl:'Menschen'},{de:'Herr',en:'gentleman / Mr',g:'m',pl:'Herren'},
 {de:'Dame',en:'lady',g:'f',pl:'Damen'},{de:'Nachbarin',en:'female neighbour',g:'f',pl:'Nachbarinnen'},
 {de:'Zwilling',en:'twin',g:'m',pl:'Zwillinge'},{de:'Großvater',en:'grandfather',g:'m',pl:'Großväter'},
 {de:'Großmutter',en:'grandmother',g:'f',pl:'Großmütter'},{de:'Schwiegermutter',en:'mother-in-law',g:'f',pl:'Schwiegermütter'},
 {de:'Schwiegervater',en:'father-in-law',g:'m',pl:'Schwiegerväter'},{de:'Neffe',en:'nephew',g:'m',pl:'Neffen'},
 {de:'Nichte',en:'niece',g:'f',pl:'Nichten'},{de:'Braut',en:'bride',g:'f',pl:'Bräute'},
 {de:'Bräutigam',en:'groom',g:'m',pl:'Bräutigame'},{de:'Hochzeit',en:'wedding',g:'f',pl:'Hochzeiten'},
 {de:'Ehe',en:'marriage',g:'f',pl:'Ehen'},{de:'Paar',en:'couple / pair',g:'n',pl:'Paare'},
 {de:'Gruppe',en:'group',g:'f',pl:'Gruppen'},{de:'Team',en:'team',g:'n',pl:'Teams'},
 {de:'Verein',en:'club / association',g:'m',pl:'Vereine'},{de:'Mitglied',en:'member',g:'n',pl:'Mitglieder'},
 {de:'Besucher',en:'visitor',g:'m',pl:'Besucher'},{de:'Publikum',en:'audience',g:'n',pl:null},
 {de:'Menge',en:'crowd / amount',g:'f',pl:'Mengen'},{de:'Bevölkerung',en:'population',g:'f',pl:'Bevölkerungen'},
 {de:'Bürger',en:'citizen',g:'m',pl:'Bürger'},{de:'Einwohner',en:'inhabitant',g:'m',pl:'Einwohner'},
 {de:'Ausländer',en:'foreigner',g:'m',pl:'Ausländer'},{de:'Tourist',en:'tourist',g:'m',pl:'Touristen'},
 {de:'Kunde',en:'customer',g:'m',pl:'Kunden'},{de:'Kundin',en:'female customer',g:'f',pl:'Kundinnen'},
 {de:'Besitzer',en:'owner',g:'m',pl:'Besitzer'},{de:'Dieb',en:'thief',g:'m',pl:'Diebe'},
 {de:'Opfer',en:'victim',g:'n',pl:'Opfer'},{de:'Kleinkind',en:'toddler',g:'n',pl:'Kleinkinder'},
 {de:'Held',en:'hero',g:'m',pl:'Helden'},{de:'König',en:'king',g:'m',pl:'Könige'},
 {de:'Königin',en:'queen',g:'f',pl:'Königinnen'},{de:'Prinz',en:'prince',g:'m',pl:'Prinzen'},
 {de:'Prinzessin',en:'princess',g:'f',pl:'Prinzessinnen'}
);

/* ===== professions ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Beruf',en:'profession',g:'m',pl:'Berufe'},{de:'Lehrerin',en:'female teacher',g:'f',pl:'Lehrerinnen'},
 {de:'Schüler',en:'pupil',g:'m',pl:'Schüler'},{de:'Schülerin',en:'female pupil',g:'f',pl:'Schülerinnen'},
 {de:'Student',en:'university student',g:'m',pl:'Studenten'},{de:'Studentin',en:'female student',g:'f',pl:'Studentinnen'},
 {de:'Professor',en:'professor',g:'m',pl:'Professoren'},{de:'Ingenieur',en:'engineer',g:'m',pl:'Ingenieure'},
 {de:'Krankenschwester',en:'nurse',g:'f',pl:'Krankenschwestern'},{de:'Zahnarzt',en:'dentist',g:'m',pl:'Zahnärzte'},
 {de:'Tierarzt',en:'veterinarian',g:'m',pl:'Tierärzte'},{de:'Anwalt',en:'lawyer',g:'m',pl:'Anwälte'},
 {de:'Richter',en:'judge',g:'m',pl:'Richter'},{de:'Verkäufer',en:'salesman',g:'m',pl:'Verkäufer'},
 {de:'Verkäuferin',en:'saleswoman',g:'f',pl:'Verkäuferinnen'},{de:'Kellner',en:'waiter',g:'m',pl:'Kellner'},
 {de:'Kellnerin',en:'waitress',g:'f',pl:'Kellnerinnen'},{de:'Friseur',en:'hairdresser',g:'m',pl:'Friseure'},
 {de:'Metzger',en:'butcher',g:'m',pl:'Metzger'},{de:'Bauer',en:'farmer',g:'m',pl:'Bauern'},
 {de:'Fischer',en:'fisherman',g:'m',pl:'Fischer'},{de:'Soldat',en:'soldier',g:'m',pl:'Soldaten'},
 {de:'Pilot',en:'pilot',g:'m',pl:'Piloten'},{de:'Fahrer',en:'driver',g:'m',pl:'Fahrer'},
 {de:'Schauspieler',en:'actor',g:'m',pl:'Schauspieler'},{de:'Sänger',en:'singer',g:'m',pl:'Sänger'},
 {de:'Sängerin',en:'female singer',g:'f',pl:'Sängerinnen'},{de:'Maler',en:'painter',g:'m',pl:'Maler'},
 {de:'Schriftsteller',en:'writer',g:'m',pl:'Schriftsteller'},{de:'Journalist',en:'journalist',g:'m',pl:'Journalisten'},
 {de:'Wissenschaftler',en:'scientist',g:'m',pl:'Wissenschaftler'},{de:'Forscher',en:'researcher',g:'m',pl:'Forscher'},
 {de:'Programmierer',en:'programmer',g:'m',pl:'Programmierer'},{de:'Künstler',en:'artist',g:'m',pl:'Künstler'},
 {de:'Musiker',en:'musician',g:'m',pl:'Musiker'},{de:'Direktor',en:'director',g:'m',pl:'Direktoren'},
 {de:'Sekretärin',en:'secretary',g:'f',pl:'Sekretärinnen'},{de:'Handwerker',en:'craftsman',g:'m',pl:'Handwerker'},
 {de:'Elektriker',en:'electrician',g:'m',pl:'Elektriker'},{de:'Mechaniker',en:'mechanic',g:'m',pl:'Mechaniker'},
 {de:'Architekt',en:'architect',g:'m',pl:'Architekten'},{de:'Apotheker',en:'pharmacist',g:'m',pl:'Apotheker'},
 {de:'Feuerwehrmann',en:'firefighter',g:'m',pl:'Feuerwehrleute'},{de:'Briefträger',en:'postman',g:'m',pl:'Briefträger'},
 {de:'Gärtner',en:'gardener',g:'m',pl:'Gärtner'},{de:'Trainer',en:'coach',g:'m',pl:'Trainer'}
);

/* ===== body & health ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Körper',en:'body',g:'m',pl:'Körper'},{de:'Arm',en:'arm',g:'m',pl:'Arme'},
 {de:'Bein',en:'leg',g:'n',pl:'Beine'},{de:'Finger',en:'finger',g:'m',pl:'Finger'},
 {de:'Daumen',en:'thumb',g:'m',pl:'Daumen'},{de:'Knie',en:'knee',g:'n',pl:'Knie'},
 {de:'Schulter',en:'shoulder',g:'f',pl:'Schultern'},{de:'Rücken',en:'back',g:'m',pl:'Rücken'},
 {de:'Haut',en:'skin',g:'f',pl:'Häute'},{de:'Blut',en:'blood',g:'n',pl:null},
 {de:'Knochen',en:'bone',g:'m',pl:'Knochen'},{de:'Muskel',en:'muscle',g:'m',pl:'Muskeln'},
 {de:'Gehirn',en:'brain',g:'n',pl:'Gehirne'},{de:'Magen',en:'stomach',g:'m',pl:'Mägen'},
 {de:'Lunge',en:'lung',g:'f',pl:'Lungen'},{de:'Zunge',en:'tongue',g:'f',pl:'Zungen'},
 {de:'Lippe',en:'lip',g:'f',pl:'Lippen'},{de:'Stirn',en:'forehead',g:'f',pl:'Stirnen'},
 {de:'Wange',en:'cheek',g:'f',pl:'Wangen'},{de:'Kinn',en:'chin',g:'n',pl:'Kinne'},
 {de:'Hals',en:'neck / throat',g:'m',pl:'Hälse'},{de:'Ellbogen',en:'elbow',g:'m',pl:'Ellbogen'},
 {de:'Zeh',en:'toe',g:'m',pl:'Zehen'},{de:'Ferse',en:'heel',g:'f',pl:'Fersen'},
 {de:'Schmerz',en:'pain',g:'m',pl:'Schmerzen'},{de:'Krankheit',en:'illness',g:'f',pl:'Krankheiten'},
 {de:'Fieber',en:'fever',g:'n',pl:null},{de:'Husten',en:'cough',g:'m',pl:null},
 {de:'Schnupfen',en:'runny nose',g:'m',pl:null},{de:'Erkältung',en:'cold (illness)',g:'f',pl:'Erkältungen'},
 {de:'Grippe',en:'flu',g:'f',pl:'Grippen'},{de:'Wunde',en:'wound',g:'f',pl:'Wunden'},
 {de:'Pflaster',en:'plaster / band-aid',g:'n',pl:'Pflaster'},{de:'Medikament',en:'medicine',g:'n',pl:'Medikamente'},
 {de:'Tablette',en:'pill',g:'f',pl:'Tabletten'},{de:'Impfung',en:'vaccination',g:'f',pl:'Impfungen'},
 {de:'Gesundheit',en:'health',g:'f',pl:null},{de:'Notfall',en:'emergency',g:'m',pl:'Notfälle'},
 {de:'Krankenwagen',en:'ambulance',g:'m',pl:'Krankenwagen'},{de:'Brustkorb',en:'chest',g:'m',pl:'Brustkörbe'},
 {de:'Hunger',en:'hunger',g:'m',pl:null},{de:'Durst',en:'thirst',g:'m',pl:null}
);

/* ===== food & drink ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Mahlzeit',en:'meal',g:'f',pl:'Mahlzeiten'},{de:'Gericht',en:'dish',g:'n',pl:'Gerichte'},
 {de:'Vorspeise',en:'starter',g:'f',pl:'Vorspeisen'},{de:'Nachtisch',en:'dessert',g:'m',pl:'Nachtische'},
 {de:'Getränk',en:'drink',g:'n',pl:'Getränke'},{de:'Saft',en:'juice',g:'m',pl:'Säfte'},
 {de:'Limonade',en:'lemonade',g:'f',pl:'Limonaden'},{de:'Kakao',en:'cocoa',g:'m',pl:null},
 {de:'Sahne',en:'cream',g:'f',pl:null},{de:'Joghurt',en:'yoghurt',g:'m',pl:'Joghurts'},
 {de:'Marmelade',en:'jam',g:'f',pl:'Marmeladen'},{de:'Brötchen',en:'bread roll',g:'n',pl:'Brötchen'},
 {de:'Müsli',en:'muesli',g:'n',pl:'Müslis'},{de:'Mehl',en:'flour',g:'n',pl:null},
 {de:'Teig',en:'dough',g:'m',pl:'Teige'},{de:'Keks',en:'biscuit',g:'m',pl:'Kekse'},
 {de:'Bonbon',en:'sweet / candy',g:'n',pl:'Bonbons'},{de:'Pizza',en:'pizza',g:'f',pl:'Pizzen'},
 {de:'Wurst',en:'sausage',g:'f',pl:'Würste'},{de:'Schinken',en:'ham',g:'m',pl:'Schinken'},
 {de:'Hähnchen',en:'chicken (food)',g:'n',pl:'Hähnchen'},{de:'Rindfleisch',en:'beef',g:'n',pl:null},
 {de:'Lachs',en:'salmon',g:'m',pl:'Lachse'},{de:'Thunfisch',en:'tuna',g:'m',pl:'Thunfische'},
 {de:'Zwiebel',en:'onion',g:'f',pl:'Zwiebeln'},{de:'Knoblauch',en:'garlic',g:'m',pl:null},
 {de:'Paprika',en:'bell pepper',g:'f',pl:'Paprikas'},{de:'Gurke',en:'cucumber',g:'f',pl:'Gurken'},
 {de:'Karotte',en:'carrot',g:'f',pl:'Karotten'},{de:'Erbse',en:'pea',g:'f',pl:'Erbsen'},
 {de:'Bohne',en:'bean',g:'f',pl:'Bohnen'},{de:'Pilz',en:'mushroom',g:'m',pl:'Pilze'},
 {de:'Spinat',en:'spinach',g:'m',pl:null},{de:'Kohl',en:'cabbage',g:'m',pl:null},
 {de:'Mais',en:'corn',g:'m',pl:null},{de:'Erdbeere',en:'strawberry',g:'f',pl:'Erdbeeren'},
 {de:'Himbeere',en:'raspberry',g:'f',pl:'Himbeeren'},{de:'Kirsche',en:'cherry',g:'f',pl:'Kirschen'},
 {de:'Pflaume',en:'plum',g:'f',pl:'Pflaumen'},{de:'Birne',en:'pear',g:'f',pl:'Birnen'},
 {de:'Pfirsich',en:'peach',g:'m',pl:'Pfirsiche'},{de:'Traube',en:'grape',g:'f',pl:'Trauben'},
 {de:'Melone',en:'melon',g:'f',pl:'Melonen'},{de:'Ananas',en:'pineapple',g:'f',pl:'Ananasse'},
 {de:'Zitrone',en:'lemon',g:'f',pl:'Zitronen'},{de:'Nuss',en:'nut',g:'f',pl:'Nüsse'},
 {de:'Mandel',en:'almond',g:'f',pl:'Mandeln'},{de:'Erdnuss',en:'peanut',g:'f',pl:'Erdnüsse'},
 {de:'Gewürz',en:'spice',g:'n',pl:'Gewürze'},{de:'Pfeffer',en:'pepper (spice)',g:'m',pl:null},
 {de:'Essig',en:'vinegar',g:'m',pl:null},{de:'Senf',en:'mustard',g:'m',pl:null},
 {de:'Soße',en:'sauce',g:'f',pl:'Soßen'},{de:'Rezept',en:'recipe',g:'n',pl:'Rezepte'},
 {de:'Speisekarte',en:'menu',g:'f',pl:'Speisekarten'},{de:'Trinkgeld',en:'tip (money)',g:'n',pl:'Trinkgelder'},
 {de:'Öl',en:'oil',g:'n',pl:'Öle'},{de:'Dose',en:'can / tin',g:'f',pl:'Dosen'},
 {de:'Flasche',en:'bottle',g:'f',pl:'Flaschen'},{de:'Becher',en:'mug / cup',g:'m',pl:'Becher'},
 {de:'Teller',en:'plate',g:'m',pl:'Teller'},{de:'Schüssel',en:'bowl',g:'f',pl:'Schüsseln'},
 {de:'Messer',en:'knife',g:'n',pl:'Messer'},{de:'Gabel',en:'fork',g:'f',pl:'Gabeln'},
 {de:'Löffel',en:'spoon',g:'m',pl:'Löffel'},{de:'Pfanne',en:'frying pan',g:'f',pl:'Pfannen'},
 {de:'Topf',en:'pot',g:'m',pl:'Töpfe'},{de:'Ofen',en:'oven',g:'m',pl:'Öfen'},
 {de:'Herd',en:'stove',g:'m',pl:'Herde'},{de:'Kühlschrank',en:'fridge',g:'m',pl:'Kühlschränke'}
);

/* ===== home & household ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Wohnung',en:'apartment',g:'f',pl:'Wohnungen'},{de:'Zuhause',en:'home',g:'n',pl:null},
 {de:'Schlafzimmer',en:'bedroom',g:'n',pl:'Schlafzimmer'},{de:'Wohnzimmer',en:'living room',g:'n',pl:'Wohnzimmer'},
 {de:'Badezimmer',en:'bathroom',g:'n',pl:'Badezimmer'},{de:'Toilette',en:'toilet',g:'f',pl:'Toiletten'},
 {de:'Balkon',en:'balcony',g:'m',pl:'Balkone'},{de:'Terrasse',en:'terrace',g:'f',pl:'Terrassen'},
 {de:'Flur',en:'hallway',g:'m',pl:'Flure'},{de:'Aufzug',en:'elevator',g:'m',pl:'Aufzüge'},
 {de:'Schrank',en:'cupboard / wardrobe',g:'m',pl:'Schränke'},{de:'Schublade',en:'drawer',g:'f',pl:'Schubladen'},
 {de:'Sessel',en:'armchair',g:'m',pl:'Sessel'},{de:'Kissen',en:'pillow',g:'n',pl:'Kissen'},
 {de:'Decke',en:'blanket / ceiling',g:'f',pl:'Decken'},{de:'Vorhang',en:'curtain',g:'m',pl:'Vorhänge'},
 {de:'Dusche',en:'shower',g:'f',pl:'Duschen'},{de:'Badewanne',en:'bathtub',g:'f',pl:'Badewannen'},
 {de:'Waschbecken',en:'sink',g:'n',pl:'Waschbecken'},{de:'Handtuch',en:'towel',g:'n',pl:'Handtücher'},
 {de:'Seife',en:'soap',g:'f',pl:'Seifen'},{de:'Zahnbürste',en:'toothbrush',g:'f',pl:'Zahnbürsten'},
 {de:'Zahnpasta',en:'toothpaste',g:'f',pl:null},{de:'Kamm',en:'comb',g:'m',pl:'Kämme'},
 {de:'Waschmaschine',en:'washing machine',g:'f',pl:'Waschmaschinen'},{de:'Staubsauger',en:'vacuum cleaner',g:'m',pl:'Staubsauger'},
 {de:'Besen',en:'broom',g:'m',pl:'Besen'},{de:'Eimer',en:'bucket',g:'m',pl:'Eimer'},
 {de:'Müll',en:'rubbish',g:'m',pl:null},{de:'Mülleimer',en:'rubbish bin',g:'m',pl:'Mülleimer'},
 {de:'Heizung',en:'heating',g:'f',pl:'Heizungen'},{de:'Steckdose',en:'power socket',g:'f',pl:'Steckdosen'},
 {de:'Batterie',en:'battery',g:'f',pl:'Batterien'},{de:'Kerze',en:'candle',g:'f',pl:'Kerzen'},
 {de:'Miete',en:'rent',g:'f',pl:'Mieten'},{de:'Vermieter',en:'landlord',g:'m',pl:'Vermieter'},
 {de:'Umzug',en:'move (relocation)',g:'m',pl:'Umzüge'},{de:'Garage',en:'garage',g:'f',pl:'Garagen'},
 {de:'Zaun',en:'fence',g:'m',pl:'Zäune'},{de:'Leiter',en:'ladder',g:'f',pl:'Leitern'},
 {de:'Werkzeug',en:'tool',g:'n',pl:'Werkzeuge'},{de:'Hammer',en:'hammer',g:'m',pl:'Hämmer'},
 {de:'Nagel',en:'nail',g:'m',pl:'Nägel'},{de:'Schraube',en:'screw',g:'f',pl:'Schrauben'}
);

/* ===== clothing ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Kleidung',en:'clothing',g:'f',pl:null},{de:'Hose',en:'trousers',g:'f',pl:'Hosen'},
 {de:'Jeans',en:'jeans',g:'f',pl:'Jeans'},{de:'Rock',en:'skirt',g:'m',pl:'Röcke'},
 {de:'Bluse',en:'blouse',g:'f',pl:'Blusen'},{de:'Pullover',en:'sweater',g:'m',pl:'Pullover'},
 {de:'Jacke',en:'jacket',g:'f',pl:'Jacken'},{de:'Mantel',en:'coat',g:'m',pl:'Mäntel'},
 {de:'Anzug',en:'suit',g:'m',pl:'Anzüge'},{de:'Krawatte',en:'tie',g:'f',pl:'Krawatten'},
 {de:'Socke',en:'sock',g:'f',pl:'Socken'},{de:'Stiefel',en:'boot',g:'m',pl:'Stiefel'},
 {de:'Sandale',en:'sandal',g:'f',pl:'Sandalen'},{de:'Hausschuh',en:'slipper',g:'m',pl:'Hausschuhe'},
 {de:'Mütze',en:'beanie / cap',g:'f',pl:'Mützen'},{de:'Hut',en:'hat',g:'m',pl:'Hüte'},
 {de:'Schal',en:'scarf',g:'m',pl:'Schals'},{de:'Handschuh',en:'glove',g:'m',pl:'Handschuhe'},
 {de:'Gürtel',en:'belt',g:'m',pl:'Gürtel'},{de:'Knopf',en:'button',g:'m',pl:'Knöpfe'},
 {de:'Reißverschluss',en:'zip',g:'m',pl:'Reißverschlüsse'},{de:'Unterwäsche',en:'underwear',g:'f',pl:null},
 {de:'Schlafanzug',en:'pyjamas',g:'m',pl:'Schlafanzüge'},{de:'Badeanzug',en:'swimsuit',g:'m',pl:'Badeanzüge'},
 {de:'Regenschirm',en:'umbrella',g:'m',pl:'Regenschirme'},{de:'Schmuck',en:'jewellery',g:'m',pl:null},
 {de:'Ring',en:'ring',g:'m',pl:'Ringe'},{de:'Kette',en:'necklace / chain',g:'f',pl:'Ketten'},
 {de:'Ohrring',en:'earring',g:'m',pl:'Ohrringe'},{de:'Armband',en:'bracelet',g:'n',pl:'Armbänder'},
 {de:'Geldbeutel',en:'wallet',g:'m',pl:'Geldbeutel'},{de:'Rucksack',en:'backpack',g:'m',pl:'Rucksäcke'},
 {de:'Koffer',en:'suitcase',g:'m',pl:'Koffer'},{de:'Größe',en:'size',g:'f',pl:'Größen'},
 {de:'Mode',en:'fashion',g:'f',pl:null},{de:'Stoff',en:'fabric',g:'m',pl:'Stoffe'},
 {de:'Wolle',en:'wool',g:'f',pl:null},{de:'Leder',en:'leather',g:'n',pl:null},
 {de:'Baumwolle',en:'cotton',g:'f',pl:null},{de:'Fleck',en:'stain',g:'m',pl:'Flecken'}
);

/* ===== school, office & technology ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Universität',en:'university',g:'f',pl:'Universitäten'},{de:'Klasse',en:'class',g:'f',pl:'Klassen'},
 {de:'Unterricht',en:'lesson / teaching',g:'m',pl:null},{de:'Hausaufgabe',en:'homework',g:'f',pl:'Hausaufgaben'},
 {de:'Prüfung',en:'exam',g:'f',pl:'Prüfungen'},{de:'Note',en:'grade / mark',g:'f',pl:'Noten'},
 {de:'Fehler',en:'mistake',g:'m',pl:'Fehler'},{de:'Übung',en:'exercise',g:'f',pl:'Übungen'},
 {de:'Beispiel',en:'example',g:'n',pl:'Beispiele'},{de:'Wörterbuch',en:'dictionary',g:'n',pl:'Wörterbücher'},
 {de:'Heft',en:'notebook',g:'n',pl:'Hefte'},{de:'Bleistift',en:'pencil',g:'m',pl:'Bleistifte'},
 {de:'Kugelschreiber',en:'ballpoint pen',g:'m',pl:'Kugelschreiber'},{de:'Radiergummi',en:'eraser',g:'m',pl:'Radiergummis'},
 {de:'Lineal',en:'ruler',g:'n',pl:'Lineale'},{de:'Tafel',en:'blackboard',g:'f',pl:'Tafeln'},
 {de:'Kreide',en:'chalk',g:'f',pl:null},{de:'Pausenhof',en:'schoolyard',g:'m',pl:'Pausenhöfe'},
 {de:'Zeugnis',en:'school report',g:'n',pl:'Zeugnisse'},{de:'Wissen',en:'knowledge',g:'n',pl:null},
 {de:'Bildung',en:'education',g:'f',pl:null},{de:'Kurs',en:'course',g:'m',pl:'Kurse'},
 {de:'Seite',en:'page',g:'f',pl:'Seiten'},{de:'Kapitel',en:'chapter',g:'n',pl:'Kapitel'},
 {de:'Geschichte',en:'history / story',g:'f',pl:'Geschichten'},{de:'Mathematik',en:'mathematics',g:'f',pl:null},
 {de:'Wissenschaft',en:'science',g:'f',pl:'Wissenschaften'},{de:'Kunst',en:'art',g:'f',pl:'Künste'},
 {de:'Büro',en:'office',g:'n',pl:'Büros'},{de:'Firma',en:'company',g:'f',pl:'Firmen'},
 {de:'Arbeit',en:'work',g:'f',pl:null},{de:'Stelle',en:'job / position',g:'f',pl:'Stellen'},
 {de:'Gehalt',en:'salary',g:'n',pl:'Gehälter'},{de:'Besprechung',en:'meeting',g:'f',pl:'Besprechungen'},
 {de:'Projekt',en:'project',g:'n',pl:'Projekte'},{de:'Bericht',en:'report',g:'m',pl:'Berichte'},
 {de:'Unterschrift',en:'signature',g:'f',pl:'Unterschriften'},{de:'Formular',en:'form (document)',g:'n',pl:'Formulare'},
 {de:'Drucker',en:'printer',g:'m',pl:'Drucker'},{de:'Bildschirm',en:'screen',g:'m',pl:'Bildschirme'},
 {de:'Tastatur',en:'keyboard',g:'f',pl:'Tastaturen'},{de:'Taste',en:'key (button)',g:'f',pl:'Tasten'},
 {de:'Internet',en:'internet',g:'n',pl:null},{de:'Webseite',en:'website',g:'f',pl:'Webseiten'},
 {de:'E-Mail',en:'email',g:'f',pl:'E-Mails'},{de:'Nachricht',en:'message / news item',g:'f',pl:'Nachrichten'},
 {de:'Anruf',en:'phone call',g:'m',pl:'Anrufe'},{de:'Nummer',en:'number',g:'f',pl:'Nummern'},
 {de:'Adresse',en:'address',g:'f',pl:'Adressen'},{de:'Passwort',en:'password',g:'n',pl:'Passwörter'},
 {de:'Datei',en:'file (computer)',g:'f',pl:'Dateien'},{de:'Foto',en:'photo',g:'n',pl:'Fotos'},
 {de:'Kamera',en:'camera',g:'f',pl:'Kameras'},{de:'Fernseher',en:'TV set',g:'m',pl:'Fernseher'},
 {de:'Radio',en:'radio',g:'n',pl:'Radios'},{de:'Kopfhörer',en:'headphones',g:'m',pl:'Kopfhörer'},
 {de:'Ladegerät',en:'charger',g:'n',pl:'Ladegeräte'},{de:'Akku',en:'rechargeable battery',g:'m',pl:'Akkus'}
);

/* ===== city, transport & travel ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Land',en:'country',g:'n',pl:'Länder'},{de:'Dorf',en:'village',g:'n',pl:'Dörfer'},
 {de:'Hauptstadt',en:'capital city',g:'f',pl:'Hauptstädte'},{de:'Zentrum',en:'centre',g:'n',pl:'Zentren'},
 {de:'Rathaus',en:'town hall',g:'n',pl:'Rathäuser'},{de:'Museum',en:'museum',g:'n',pl:'Museen'},
 {de:'Bibliothek',en:'library',g:'f',pl:'Bibliotheken'},{de:'Theater',en:'theatre',g:'n',pl:'Theater'},
 {de:'Kino',en:'cinema',g:'n',pl:'Kinos'},{de:'Schwimmbad',en:'swimming pool',g:'n',pl:'Schwimmbäder'},
 {de:'Stadion',en:'stadium',g:'n',pl:'Stadien'},{de:'Zoo',en:'zoo',g:'m',pl:'Zoos'},
 {de:'Park',en:'park',g:'m',pl:'Parks'},{de:'Spielplatz',en:'playground',g:'m',pl:'Spielplätze'},
 {de:'Friedhof',en:'cemetery',g:'m',pl:'Friedhöfe'},{de:'Schloss',en:'castle / lock',g:'n',pl:'Schlösser'},
 {de:'Turm',en:'tower',g:'m',pl:'Türme'},{de:'Denkmal',en:'monument',g:'n',pl:'Denkmäler'},
 {de:'Bank',en:'bank / bench',g:'f',pl:'Banken'},{de:'Post',en:'post office',g:'f',pl:null},
 {de:'Polizei',en:'police',g:'f',pl:null},{de:'Feuerwehr',en:'fire brigade',g:'f',pl:'Feuerwehren'},
 {de:'Tankstelle',en:'petrol station',g:'f',pl:'Tankstellen'},{de:'Parkplatz',en:'car park',g:'m',pl:'Parkplätze'},
 {de:'Kreuzung',en:'crossroads',g:'f',pl:'Kreuzungen'},{de:'Bürgersteig',en:'pavement',g:'m',pl:'Bürgersteige'},
 {de:'Autobahn',en:'motorway',g:'f',pl:'Autobahnen'},{de:'Stau',en:'traffic jam',g:'m',pl:'Staus'},
 {de:'Verkehr',en:'traffic',g:'m',pl:null},{de:'Unfall',en:'accident',g:'m',pl:'Unfälle'},
 {de:'Führerschein',en:'driving licence',g:'m',pl:'Führerscheine'},{de:'Motorrad',en:'motorbike',g:'n',pl:'Motorräder'},
 {de:'Lastwagen',en:'lorry / truck',g:'m',pl:'Lastwagen'},{de:'Straßenbahn',en:'tram',g:'f',pl:'Straßenbahnen'},
 {de:'U-Bahn',en:'underground / subway',g:'f',pl:'U-Bahnen'},{de:'Taxi',en:'taxi',g:'n',pl:'Taxis'},
 {de:'Hubschrauber',en:'helicopter',g:'m',pl:'Hubschrauber'},{de:'Boot',en:'boat',g:'n',pl:'Boote'},
 {de:'Hafen',en:'harbour',g:'m',pl:'Häfen'},{de:'Gleis',en:'platform / track',g:'n',pl:'Gleise'},
 {de:'Fahrkarte',en:'ticket (transport)',g:'f',pl:'Fahrkarten'},{de:'Fahrplan',en:'timetable',g:'m',pl:'Fahrpläne'},
 {de:'Abfahrt',en:'departure',g:'f',pl:'Abfahrten'},{de:'Ankunft',en:'arrival',g:'f',pl:'Ankünfte'},
 {de:'Verspätung',en:'delay',g:'f',pl:'Verspätungen'},{de:'Richtung',en:'direction',g:'f',pl:'Richtungen'},
 {de:'Karte',en:'card / map',g:'f',pl:'Karten'},{de:'Grenze',en:'border',g:'f',pl:'Grenzen'},
 {de:'Pass',en:'passport',g:'m',pl:'Pässe'},{de:'Visum',en:'visa',g:'n',pl:'Visa'},
 {de:'Gepäck',en:'luggage',g:'n',pl:null},{de:'Sehenswürdigkeit',en:'sight / attraction',g:'f',pl:'Sehenswürdigkeiten'},
 {de:'Aussicht',en:'view',g:'f',pl:'Aussichten'},{de:'Abenteuer',en:'adventure',g:'n',pl:'Abenteuer'},
 {de:'Ausflug',en:'excursion',g:'m',pl:'Ausflüge'},{de:'Strand',en:'beach',g:'m',pl:'Strände'},
 {de:'Souvenir',en:'souvenir',g:'n',pl:'Souvenirs'},{de:'Zelt',en:'tent',g:'n',pl:'Zelte'}
);

/* ===== nature & weather ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Natur',en:'nature',g:'f',pl:null},{de:'Umwelt',en:'environment',g:'f',pl:null},
 {de:'Erde',en:'earth / soil',g:'f',pl:null},{de:'Welt',en:'world',g:'f',pl:'Welten'},
 {de:'Himmel',en:'sky / heaven',g:'m',pl:null},{de:'Wolke',en:'cloud',g:'f',pl:'Wolken'},
 {de:'Wind',en:'wind',g:'m',pl:'Winde'},{de:'Sturm',en:'storm',g:'m',pl:'Stürme'},
 {de:'Gewitter',en:'thunderstorm',g:'n',pl:'Gewitter'},{de:'Blitz',en:'lightning',g:'m',pl:'Blitze'},
 {de:'Donner',en:'thunder',g:'m',pl:null},{de:'Nebel',en:'fog',g:'m',pl:null},
 {de:'Regenbogen',en:'rainbow',g:'m',pl:'Regenbogen'},{de:'Hitze',en:'heat',g:'f',pl:null},
 {de:'Kälte',en:'cold (temperature)',g:'f',pl:null},{de:'Temperatur',en:'temperature',g:'f',pl:'Temperaturen'},
 {de:'Grad',en:'degree',g:'m',pl:'Grade'},{de:'Licht',en:'light',g:'n',pl:'Lichter'},
 {de:'Schatten',en:'shadow',g:'m',pl:'Schatten'},{de:'Feuer',en:'fire',g:'n',pl:'Feuer'},
 {de:'Luft',en:'air',g:'f',pl:null},{de:'See',en:'lake',g:'m',pl:'Seen'},
 {de:'Teich',en:'pond',g:'m',pl:'Teiche'},{de:'Bach',en:'stream',g:'m',pl:'Bäche'},
 {de:'Welle',en:'wave',g:'f',pl:'Wellen'},{de:'Küste',en:'coast',g:'f',pl:'Küsten'},
 {de:'Ufer',en:'shore / bank',g:'n',pl:'Ufer'},{de:'Wüste',en:'desert',g:'f',pl:'Wüsten'},
 {de:'Hügel',en:'hill',g:'m',pl:'Hügel'},{de:'Tal',en:'valley',g:'n',pl:'Täler'},
 {de:'Felsen',en:'rock / cliff',g:'m',pl:'Felsen'},{de:'Stein',en:'stone',g:'m',pl:'Steine'},
 {de:'Sand',en:'sand',g:'m',pl:null},{de:'Gras',en:'grass',g:'n',pl:'Gräser'},
 {de:'Blatt',en:'leaf / sheet',g:'n',pl:'Blätter'},{de:'Ast',en:'branch',g:'m',pl:'Äste'},
 {de:'Wurzel',en:'root',g:'f',pl:'Wurzeln'},{de:'Pflanze',en:'plant',g:'f',pl:'Pflanzen'},
 {de:'Rose',en:'rose',g:'f',pl:'Rosen'},{de:'Feld',en:'field',g:'n',pl:'Felder'},
 {de:'Wiese',en:'meadow',g:'f',pl:'Wiesen'},{de:'Bauernhof',en:'farm',g:'m',pl:'Bauernhöfe'},
 {de:'Ernte',en:'harvest',g:'f',pl:'Ernten'},{de:'Insekt',en:'insect',g:'n',pl:'Insekten'}
);

/* ===== animals ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Tier',en:'animal',g:'n',pl:'Tiere'},{de:'Haustier',en:'pet',g:'n',pl:'Haustiere'},
 {de:'Elefant',en:'elephant',g:'m',pl:'Elefanten'},{de:'Tiger',en:'tiger',g:'m',pl:'Tiger'},
 {de:'Giraffe',en:'giraffe',g:'f',pl:'Giraffen'},{de:'Kamel',en:'camel',g:'n',pl:'Kamele'},
 {de:'Wolf',en:'wolf',g:'m',pl:'Wölfe'},{de:'Fuchs',en:'fox',g:'m',pl:'Füchse'},
 {de:'Hase',en:'hare',g:'m',pl:'Hasen'},{de:'Kaninchen',en:'rabbit',g:'n',pl:'Kaninchen'},
 {de:'Eichhörnchen',en:'squirrel',g:'n',pl:'Eichhörnchen'},{de:'Igel',en:'hedgehog',g:'m',pl:'Igel'},
 {de:'Hirsch',en:'deer',g:'m',pl:'Hirsche'},{de:'Ziege',en:'goat',g:'f',pl:'Ziegen'},
 {de:'Esel',en:'donkey',g:'m',pl:'Esel'},{de:'Huhn',en:'hen / chicken',g:'n',pl:'Hühner'},
 {de:'Hahn',en:'rooster / tap',g:'m',pl:'Hähne'},{de:'Ente',en:'duck',g:'f',pl:'Enten'},
 {de:'Gans',en:'goose',g:'f',pl:'Gänse'},{de:'Schwan',en:'swan',g:'m',pl:'Schwäne'},
 {de:'Eule',en:'owl',g:'f',pl:'Eulen'},{de:'Adler',en:'eagle',g:'m',pl:'Adler'},
 {de:'Taube',en:'pigeon / dove',g:'f',pl:'Tauben'},{de:'Papagei',en:'parrot',g:'m',pl:'Papageien'},
 {de:'Pinguin',en:'penguin',g:'m',pl:'Pinguine'},{de:'Delfin',en:'dolphin',g:'m',pl:'Delfine'},
 {de:'Wal',en:'whale',g:'m',pl:'Wale'},{de:'Hai',en:'shark',g:'m',pl:'Haie'},
 {de:'Frosch',en:'frog',g:'m',pl:'Frösche'},{de:'Schlange',en:'snake / queue',g:'f',pl:'Schlangen'},
 {de:'Schildkröte',en:'turtle',g:'f',pl:'Schildkröten'},{de:'Eidechse',en:'lizard',g:'f',pl:'Eidechsen'},
 {de:'Biene',en:'bee',g:'f',pl:'Bienen'},{de:'Wespe',en:'wasp',g:'f',pl:'Wespen'},
 {de:'Ameise',en:'ant',g:'f',pl:'Ameisen'},{de:'Fliege',en:'fly',g:'f',pl:'Fliegen'},
 {de:'Mücke',en:'mosquito',g:'f',pl:'Mücken'},{de:'Schmetterling',en:'butterfly',g:'m',pl:'Schmetterlinge'},
 {de:'Spinne',en:'spider',g:'f',pl:'Spinnen'},{de:'Käfer',en:'beetle',g:'m',pl:'Käfer'},
 {de:'Schnecke',en:'snail',g:'f',pl:'Schnecken'},{de:'Wurm',en:'worm',g:'m',pl:'Würmer'},
 {de:'Feder',en:'feather',g:'f',pl:'Federn'},{de:'Flügel',en:'wing',g:'m',pl:'Flügel'},
 {de:'Schwanz',en:'tail',g:'m',pl:'Schwänze'},{de:'Fell',en:'fur',g:'n',pl:'Felle'},
 {de:'Käfig',en:'cage',g:'m',pl:'Käfige'},{de:'Nest',en:'nest',g:'n',pl:'Nester'}
);

/* ===== sport, hobby, music & media ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Sport',en:'sport',g:'m',pl:null},{de:'Fußball',en:'football',g:'m',pl:'Fußbälle'},
 {de:'Tennis',en:'tennis',g:'n',pl:null},{de:'Basketball',en:'basketball',g:'m',pl:'Basketbälle'},
 {de:'Mannschaft',en:'team (sports)',g:'f',pl:'Mannschaften'},{de:'Spieler',en:'player',g:'m',pl:'Spieler'},
 {de:'Tor',en:'goal / gate',g:'n',pl:'Tore'},{de:'Sieg',en:'victory',g:'m',pl:'Siege'},
 {de:'Niederlage',en:'defeat',g:'f',pl:'Niederlagen'},{de:'Wettkampf',en:'competition',g:'m',pl:'Wettkämpfe'},
 {de:'Preis',en:'prize / price',g:'m',pl:'Preise'},{de:'Medaille',en:'medal',g:'f',pl:'Medaillen'},
 {de:'Training',en:'training',g:'n',pl:null},{de:'Fitnessstudio',en:'gym',g:'n',pl:'Fitnessstudios'},
 {de:'Lauf',en:'run',g:'m',pl:'Läufe'},{de:'Wanderung',en:'hike',g:'f',pl:'Wanderungen'},
 {de:'Angeln',en:'fishing',g:'n',pl:null},{de:'Schach',en:'chess',g:'n',pl:null},
 {de:'Würfel',en:'dice / cube',g:'m',pl:'Würfel'},{de:'Puppe',en:'doll',g:'f',pl:'Puppen'},
 {de:'Spielzeug',en:'toy',g:'n',pl:'Spielzeuge'},{de:'Hobby',en:'hobby',g:'n',pl:'Hobbys'},
 {de:'Freizeit',en:'free time',g:'f',pl:null},{de:'Konzert',en:'concert',g:'n',pl:'Konzerte'},
 {de:'Band',en:'band (music)',g:'f',pl:'Bands'},{de:'Bühne',en:'stage',g:'f',pl:'Bühnen'},
 {de:'Gitarre',en:'guitar',g:'f',pl:'Gitarren'},{de:'Klavier',en:'piano',g:'n',pl:'Klaviere'},
 {de:'Geige',en:'violin',g:'f',pl:'Geigen'},{de:'Trommel',en:'drum',g:'f',pl:'Trommeln'},
 {de:'Flöte',en:'flute',g:'f',pl:'Flöten'},{de:'Stimme',en:'voice',g:'f',pl:'Stimmen'},
 {de:'Tanz',en:'dance',g:'m',pl:'Tänze'},{de:'Gemälde',en:'painting',g:'n',pl:'Gemälde'},
 {de:'Zeichnung',en:'drawing',g:'f',pl:'Zeichnungen'},{de:'Roman',en:'novel',g:'m',pl:'Romane'},
 {de:'Gedicht',en:'poem',g:'n',pl:'Gedichte'},{de:'Märchen',en:'fairy tale',g:'n',pl:'Märchen'},
 {de:'Zeitschrift',en:'magazine',g:'f',pl:'Zeitschriften'},{de:'Schlagzeile',en:'headline',g:'f',pl:'Schlagzeilen'},
 {de:'Werbung',en:'advertising',g:'f',pl:null},{de:'Sendung',en:'TV programme',g:'f',pl:'Sendungen'},
 {de:'Serie',en:'series',g:'f',pl:'Serien'},{de:'Witz',en:'joke',g:'m',pl:'Witze'}
);

/* ===== shopping & money ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Geschäft',en:'shop / business',g:'n',pl:'Geschäfte'},{de:'Laden',en:'shop',g:'m',pl:'Läden'},
 {de:'Kaufhaus',en:'department store',g:'n',pl:'Kaufhäuser'},{de:'Kiosk',en:'kiosk',g:'m',pl:'Kioske'},
 {de:'Einkauf',en:'purchase / shopping',g:'m',pl:'Einkäufe'},{de:'Einkaufswagen',en:'shopping trolley',g:'m',pl:'Einkaufswagen'},
 {de:'Kasse',en:'checkout / till',g:'f',pl:'Kassen'},{de:'Quittung',en:'receipt',g:'f',pl:'Quittungen'},
 {de:'Angebot',en:'offer',g:'n',pl:'Angebote'},{de:'Rabatt',en:'discount',g:'m',pl:'Rabatte'},
 {de:'Euro',en:'euro',g:'m',pl:'Euros'},{de:'Cent',en:'cent',g:'m',pl:'Cents'},
 {de:'Münze',en:'coin',g:'f',pl:'Münzen'},{de:'Schein',en:'banknote',g:'m',pl:'Scheine'},
 {de:'Bargeld',en:'cash',g:'n',pl:null},{de:'Kreditkarte',en:'credit card',g:'f',pl:'Kreditkarten'},
 {de:'Konto',en:'bank account',g:'n',pl:'Konten'},{de:'Steuer',en:'tax',g:'f',pl:'Steuern'},
 {de:'Schulden',en:'debts',g:'f',pl:'Schulden'},{de:'Ersparnis',en:'saving',g:'f',pl:'Ersparnisse'},
 {de:'Ausgabe',en:'expense / edition',g:'f',pl:'Ausgaben'},{de:'Einkommen',en:'income',g:'n',pl:'Einkommen'},
 {de:'Versicherung',en:'insurance',g:'f',pl:'Versicherungen'},{de:'Vertrag',en:'contract',g:'m',pl:'Verträge'},
 {de:'Kosten',en:'costs',g:'f',pl:'Kosten'},{de:'Wert',en:'value',g:'m',pl:'Werte'},
 {de:'Qualität',en:'quality',g:'f',pl:'Qualitäten'},{de:'Marke',en:'brand',g:'f',pl:'Marken'},
 {de:'Paket',en:'parcel',g:'n',pl:'Pakete'},{de:'Lieferung',en:'delivery',g:'f',pl:'Lieferungen'}
);

/* ===== feelings & abstract ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Gefühl',en:'feeling',g:'n',pl:'Gefühle'},{de:'Liebe',en:'love',g:'f',pl:null},
 {de:'Glück',en:'luck / happiness',g:'n',pl:null},{de:'Freude',en:'joy',g:'f',pl:'Freuden'},
 {de:'Angst',en:'fear',g:'f',pl:'Ängste'},{de:'Wut',en:'anger',g:'f',pl:null},
 {de:'Trauer',en:'grief',g:'f',pl:null},{de:'Hoffnung',en:'hope',g:'f',pl:'Hoffnungen'},
 {de:'Traum',en:'dream',g:'m',pl:'Träume'},{de:'Wunsch',en:'wish',g:'m',pl:'Wünsche'},
 {de:'Ziel',en:'goal / aim',g:'n',pl:'Ziele'},{de:'Plan',en:'plan',g:'m',pl:'Pläne'},
 {de:'Idee',en:'idea',g:'f',pl:'Ideen'},{de:'Gedanke',en:'thought',g:'m',pl:'Gedanken'},
 {de:'Meinung',en:'opinion',g:'f',pl:'Meinungen'},{de:'Grund',en:'reason',g:'m',pl:'Gründe'},
 {de:'Problem',en:'problem',g:'n',pl:'Probleme'},{de:'Lösung',en:'solution',g:'f',pl:'Lösungen'},
 {de:'Entscheidung',en:'decision',g:'f',pl:'Entscheidungen'},{de:'Wahl',en:'choice / election',g:'f',pl:'Wahlen'},
 {de:'Möglichkeit',en:'possibility',g:'f',pl:'Möglichkeiten'},{de:'Chance',en:'chance',g:'f',pl:'Chancen'},
 {de:'Erfolg',en:'success',g:'m',pl:'Erfolge'},{de:'Misserfolg',en:'failure',g:'m',pl:'Misserfolge'},
 {de:'Erfahrung',en:'experience',g:'f',pl:'Erfahrungen'},{de:'Erinnerung',en:'memory',g:'f',pl:'Erinnerungen'},
 {de:'Geheimnis',en:'secret',g:'n',pl:'Geheimnisse'},{de:'Wahrheit',en:'truth',g:'f',pl:'Wahrheiten'},
 {de:'Lüge',en:'lie',g:'f',pl:'Lügen'},{de:'Recht',en:'right / law',g:'n',pl:'Rechte'},
 {de:'Pflicht',en:'duty',g:'f',pl:'Pflichten'},{de:'Regel',en:'rule',g:'f',pl:'Regeln'},
 {de:'Gesetz',en:'law',g:'n',pl:'Gesetze'},{de:'Freiheit',en:'freedom',g:'f',pl:'Freiheiten'},
 {de:'Frieden',en:'peace',g:'m',pl:null},{de:'Krieg',en:'war',g:'m',pl:'Kriege'},
 {de:'Gewalt',en:'violence',g:'f',pl:null},{de:'Mut',en:'courage',g:'m',pl:null},
 {de:'Kraft',en:'strength',g:'f',pl:'Kräfte'},{de:'Energie',en:'energy',g:'f',pl:'Energien'},
 {de:'Ruhe',en:'quiet / rest',g:'f',pl:null},{de:'Lärm',en:'noise',g:'m',pl:null},
 {de:'Geräusch',en:'sound',g:'n',pl:'Geräusche'},{de:'Duft',en:'scent',g:'m',pl:'Düfte'},
 {de:'Geschmack',en:'taste',g:'m',pl:'Geschmäcker'},{de:'Gewicht',en:'weight',g:'n',pl:'Gewichte'},
 {de:'Höhe',en:'height',g:'f',pl:'Höhen'},{de:'Breite',en:'width',g:'f',pl:'Breiten'},
 {de:'Länge',en:'length',g:'f',pl:'Längen'},{de:'Entfernung',en:'distance',g:'f',pl:'Entfernungen'},
 {de:'Geschwindigkeit',en:'speed',g:'f',pl:'Geschwindigkeiten'},{de:'Alter',en:'age',g:'n',pl:null},
 {de:'Leben',en:'life',g:'n',pl:'Leben'},{de:'Tod',en:'death',g:'m',pl:'Tode'},
 {de:'Geburt',en:'birth',g:'f',pl:'Geburten'},{de:'Name',en:'name',g:'m',pl:'Namen'},
 {de:'Beispiel',en:'example',g:'n',pl:'Beispiele'},{de:'Unterschied',en:'difference',g:'m',pl:'Unterschiede'},
 {de:'Ähnlichkeit',en:'similarity',g:'f',pl:'Ähnlichkeiten'},{de:'Ordnung',en:'order / tidiness',g:'f',pl:null},
 {de:'Zufall',en:'coincidence',g:'m',pl:'Zufälle'},{de:'Gefahr',en:'danger',g:'f',pl:'Gefahren'},
 {de:'Sicherheit',en:'safety',g:'f',pl:null},{de:'Hilfe',en:'help',g:'f',pl:'Hilfen'},
 {de:'Rat',en:'advice',g:'m',pl:'Ratschläge'},{de:'Tipp',en:'tip / hint',g:'m',pl:'Tipps'},
 {de:'Nachbarschaft',en:'neighbourhood',g:'f',pl:'Nachbarschaften'},{de:'Gesellschaft',en:'society',g:'f',pl:'Gesellschaften'},
 {de:'Politik',en:'politics',g:'f',pl:null},{de:'Regierung',en:'government',g:'f',pl:'Regierungen'},
 {de:'Religion',en:'religion',g:'f',pl:'Religionen'},{de:'Kultur',en:'culture',g:'f',pl:'Kulturen'},
 {de:'Tradition',en:'tradition',g:'f',pl:'Traditionen'},{de:'Fest',en:'festival / party',g:'n',pl:'Feste'},
 {de:'Feier',en:'celebration',g:'f',pl:'Feiern'},{de:'Geschenk',en:'present / gift',g:'n',pl:'Geschenke'},
 {de:'Überraschung',en:'surprise',g:'f',pl:'Überraschungen'},{de:'Einladung',en:'invitation',g:'f',pl:'Einladungen'},
 {de:'Besuch',en:'visit',g:'m',pl:'Besuche'},{de:'Gespräch',en:'conversation',g:'n',pl:'Gespräche'},
 {de:'Streit',en:'argument',g:'m',pl:null},{de:'Verabredung',en:'date / appointment',g:'f',pl:'Verabredungen'},
 {de:'Versprechen',en:'promise',g:'n',pl:'Versprechen'},{de:'Aufgabe',en:'task',g:'f',pl:'Aufgaben'},
 {de:'Arbeitgeber',en:'employer',g:'m',pl:'Arbeitgeber'},{de:'Bewerbung',en:'job application',g:'f',pl:'Bewerbungen'},
 {de:'Lebenslauf',en:'CV',g:'m',pl:'Lebensläufe'},{de:'Interview',en:'interview',g:'n',pl:'Interviews'},
 {de:'Anfang',en:'start',g:'m',pl:'Anfänge'},{de:'Schluss',en:'ending / conclusion',g:'m',pl:'Schlüsse'},
 {de:'Teil',en:'part',g:'m',pl:'Teile'},{de:'Stück',en:'piece',g:'n',pl:'Stücke'},
 {de:'Hälfte',en:'half',g:'f',pl:'Hälften'},{de:'Viertel',en:'quarter',g:'n',pl:'Viertel'},
 {de:'Doppelte',en:'double',g:'n',pl:null},{de:'Reihe',en:'row / series',g:'f',pl:'Reihen'},
 {de:'Liste',en:'list',g:'f',pl:'Listen'},{de:'Zettel',en:'note / slip',g:'m',pl:'Zettel'},
 {de:'Schachtel',en:'box (small)',g:'f',pl:'Schachteln'},{de:'Kiste',en:'crate / box',g:'f',pl:'Kisten'},
 {de:'Sack',en:'sack',g:'m',pl:'Säcke'},{de:'Faden',en:'thread',g:'m',pl:'Fäden'},
 {de:'Seil',en:'rope',g:'n',pl:'Seile'},{de:'Loch',en:'hole',g:'n',pl:'Löcher'},
 {de:'Rand',en:'edge',g:'m',pl:'Ränder'},{de:'Mitte',en:'middle',g:'f',pl:null},
 {de:'Seite',en:'side / page',g:'f',pl:'Seiten'},{de:'Oberfläche',en:'surface',g:'f',pl:'Oberflächen'},
 {de:'Farbe',en:'colour / paint',g:'f',pl:'Farben'},{de:'Form',en:'shape',g:'f',pl:'Formen'},
 {de:'Kreis',en:'circle',g:'m',pl:'Kreise'},{de:'Quadrat',en:'square (shape)',g:'n',pl:'Quadrate'},
 {de:'Linie',en:'line',g:'f',pl:'Linien'},{de:'Punkt',en:'point / dot',g:'m',pl:'Punkte'},
 {de:'Zeichen',en:'sign / symbol',g:'n',pl:'Zeichen'},{de:'Schild',en:'sign (board)',g:'n',pl:'Schilder'},
 {de:'Glas',en:'glass (material)',g:'n',pl:'Gläser'},{de:'Holz',en:'wood',g:'n',pl:'Hölzer'},
 {de:'Metall',en:'metal',g:'n',pl:'Metalle'},{de:'Eisen',en:'iron',g:'n',pl:null},
 {de:'Gold',en:'gold',g:'n',pl:null},{de:'Silber',en:'silver',g:'n',pl:null},
 {de:'Plastik',en:'plastic',g:'n',pl:null},{de:'Staub',en:'dust',g:'m',pl:null}
);

/* ===== everyday objects & misc ===== */
EXTRA_VOCAB.nouns.push(
 {de:'Ding',en:'thing',g:'n',pl:'Dinge'},{de:'Sache',en:'thing / matter',g:'f',pl:'Sachen'},
 {de:'Gegenstand',en:'object',g:'m',pl:'Gegenstände'},{de:'Maschine',en:'machine',g:'f',pl:'Maschinen'},
 {de:'Gerät',en:'device',g:'n',pl:'Geräte'},{de:'Motor',en:'engine',g:'m',pl:'Motoren'},
 {de:'Rad',en:'wheel',g:'n',pl:'Räder'},{de:'Reifen',en:'tyre',g:'m',pl:'Reifen'},
 {de:'Bremse',en:'brake',g:'f',pl:'Bremsen'},{de:'Tank',en:'fuel tank',g:'m',pl:'Tanks'},
 {de:'Benzin',en:'petrol',g:'n',pl:null},{de:'Fahrstuhl',en:'lift',g:'m',pl:'Fahrstühle'},
 {de:'Rolltreppe',en:'escalator',g:'f',pl:'Rolltreppen'},{de:'Eingang',en:'entrance',g:'m',pl:'Eingänge'},
 {de:'Ausgang',en:'exit',g:'m',pl:'Ausgänge'},{de:'Notausgang',en:'emergency exit',g:'m',pl:'Notausgänge'},
 {de:'Klingel',en:'doorbell',g:'f',pl:'Klingeln'},{de:'Briefkasten',en:'letterbox',g:'m',pl:'Briefkästen'},
 {de:'Umschlag',en:'envelope',g:'m',pl:'Umschläge'},{de:'Briefmarke',en:'stamp',g:'f',pl:'Briefmarken'},
 {de:'Postkarte',en:'postcard',g:'f',pl:'Postkarten'},{de:'Feuerzeug',en:'lighter',g:'n',pl:'Feuerzeuge'},
 {de:'Streichholz',en:'match (fire)',g:'n',pl:'Streichhölzer'},{de:'Aschenbecher',en:'ashtray',g:'m',pl:'Aschenbecher'},
 {de:'Zigarette',en:'cigarette',g:'f',pl:'Zigaretten'},{de:'Tabak',en:'tobacco',g:'m',pl:null},
 {de:'Alkohol',en:'alcohol',g:'m',pl:null},{de:'Droge',en:'drug',g:'f',pl:'Drogen'},
 {de:'Gift',en:'poison',g:'n',pl:'Gifte'},{de:'Rauch',en:'smoke',g:'m',pl:null},
 {de:'Flamme',en:'flame',g:'f',pl:'Flammen'},{de:'Asche',en:'ash',g:'f',pl:null},
 {de:'Kohle',en:'coal',g:'f',pl:'Kohlen'},{de:'Strom',en:'electricity / current',g:'m',pl:null},
 {de:'Kabel',en:'cable',g:'n',pl:'Kabel'},{de:'Draht',en:'wire',g:'m',pl:'Drähte'},
 {de:'Rohr',en:'pipe',g:'n',pl:'Rohre'},{de:'Pumpe',en:'pump',g:'f',pl:'Pumpen'},
 {de:'Fabrik',en:'factory',g:'f',pl:'Fabriken'},{de:'Lager',en:'warehouse / camp',g:'n',pl:'Lager'},
 {de:'Werkstatt',en:'workshop',g:'f',pl:'Werkstätten'},{de:'Baustelle',en:'construction site',g:'f',pl:'Baustellen'},
 {de:'Kran',en:'crane (machine)',g:'m',pl:'Kräne'},{de:'Ziegel',en:'brick',g:'m',pl:'Ziegel'},
 {de:'Beton',en:'concrete',g:'m',pl:null},{de:'Mauer',en:'wall (outdoor)',g:'f',pl:'Mauern'},
 {de:'Säule',en:'column',g:'f',pl:'Säulen'},{de:'Halle',en:'hall',g:'f',pl:'Hallen'},
 {de:'Saal',en:'large hall',g:'m',pl:'Säle'},{de:'Keller',en:'cellar',g:'m',pl:'Keller'},
 {de:'Dachboden',en:'attic',g:'m',pl:'Dachböden'},{de:'Kirchturm',en:'church tower',g:'m',pl:'Kirchtürme'},
 {de:'Glocke',en:'bell',g:'f',pl:'Glocken'},{de:'Uhrzeit',en:'time of day',g:'f',pl:'Uhrzeiten'},
 {de:'Armbanduhr',en:'wristwatch',g:'f',pl:'Armbanduhren'},{de:'Taschenlampe',en:'torch / flashlight',g:'f',pl:'Taschenlampen'},
 {de:'Lupe',en:'magnifying glass',g:'f',pl:'Lupen'},{de:'Fernglas',en:'binoculars',g:'n',pl:'Ferngläser'},
 {de:'Kompass',en:'compass',g:'m',pl:'Kompasse'},{de:'Anker',en:'anchor',g:'m',pl:'Anker'},
 {de:'Segel',en:'sail',g:'n',pl:'Segel'},{de:'Ruder',en:'oar / rudder',g:'n',pl:'Ruder'},
 {de:'Fahne',en:'flag',g:'f',pl:'Fahnen'},{de:'Krone',en:'crown',g:'f',pl:'Kronen'},
 {de:'Schwert',en:'sword',g:'n',pl:'Schwerter'},{de:'Pfeil',en:'arrow',g:'m',pl:'Pfeile'},
 {de:'Bogen',en:'bow / arc',g:'m',pl:'Bögen'},{de:'Schatz',en:'treasure / darling',g:'m',pl:'Schätze'},
 {de:'Muschel',en:'seashell',g:'f',pl:'Muscheln'},{de:'Perle',en:'pearl',g:'f',pl:'Perlen'},
 {de:'Diamant',en:'diamond',g:'m',pl:'Diamanten'},{de:'Ballon',en:'balloon',g:'m',pl:'Ballons'},
 {de:'Drachen',en:'kite',g:'m',pl:'Drachen'},{de:'Rätsel',en:'puzzle / riddle',g:'n',pl:'Rätsel'},
 {de:'Quiz',en:'quiz',g:'n',pl:'Quizze'},{de:'Wettbewerb',en:'contest',g:'m',pl:'Wettbewerbe'},
 {de:'Regal',en:'shelf unit',g:'n',pl:'Regale'},{de:'Haken',en:'hook',g:'m',pl:'Haken'},
 {de:'Griff',en:'handle',g:'m',pl:'Griffe'},{de:'Deckel',en:'lid',g:'m',pl:'Deckel'},
 {de:'Rahmen',en:'frame',g:'m',pl:'Rahmen'},{de:'Spiegelbild',en:'reflection',g:'n',pl:'Spiegelbilder'},
 {de:'Stufe',en:'step (stair)',g:'f',pl:'Stufen'},{de:'Geländer',en:'railing',g:'n',pl:'Geländer'},
 {de:'Tunnel',en:'tunnel',g:'m',pl:'Tunnel'},{de:'Höhle',en:'cave',g:'f',pl:'Höhlen'},
 {de:'Gipfel',en:'summit',g:'m',pl:'Gipfel'},{de:'Vulkan',en:'volcano',g:'m',pl:'Vulkane'},
 {de:'Erdbeben',en:'earthquake',g:'n',pl:'Erdbeben'},{de:'Flut',en:'flood / high tide',g:'f',pl:'Fluten'},
 {de:'Tropfen',en:'drop (liquid)',g:'m',pl:'Tropfen'},{de:'Pfütze',en:'puddle',g:'f',pl:'Pfützen'},
 {de:'Eiswürfel',en:'ice cube',g:'m',pl:'Eiswürfel'},{de:'Dampf',en:'steam',g:'m',pl:null}
);

/* ===== verbs (pt = Präteritum er-form, pp = Partizip II) ===== */
EXTRA_VOCAB.verbs.push(
 {inf:'leben',en:'to live (be alive)',pt:'lebte',pp:'gelebt',aux:'haben'},
 {inf:'lachen',en:'to laugh',pt:'lachte',pp:'gelacht',aux:'haben'},
 {inf:'weinen',en:'to cry',pt:'weinte',pp:'geweint',aux:'haben'},
 {inf:'schauen',en:'to look',pt:'schaute',pp:'geschaut',aux:'haben'},
 {inf:'holen',en:'to fetch',pt:'holte',pp:'geholt',aux:'haben'},
 {inf:'legen',en:'to lay / put',pt:'legte',pp:'gelegt',aux:'haben'},
 {inf:'stellen',en:'to place (upright)',pt:'stellte',pp:'gestellt',aux:'haben'},
 {inf:'setzen',en:'to set / seat',du:'setzt',er:'setzt',pt:'setzte',pp:'gesetzt',aux:'haben'},
 {inf:'hängen',en:'to hang',pt:'hängte',pp:'gehängt',aux:'haben'},
 {inf:'packen',en:'to pack',pt:'packte',pp:'gepackt',aux:'haben'},
 {inf:'putzen',en:'to clean',du:'putzt',er:'putzt',pt:'putzte',pp:'geputzt',aux:'haben'},
 {inf:'backen',en:'to bake',du:'backst',er:'backt',pt:'backte',pp:'gebacken',aux:'haben'},
 {inf:'braten',en:'to fry / roast',du:'brätst',er:'brät',pt:'briet',pp:'gebraten',aux:'haben'},
 {inf:'schneiden',en:'to cut',pt:'schnitt',pp:'geschnitten',aux:'haben'},
 {inf:'gießen',en:'to pour / water',du:'gießt',er:'gießt',pt:'goss',pp:'gegossen',aux:'haben'},
 {inf:'mischen',en:'to mix',du:'mischst',er:'mischt',pt:'mischte',pp:'gemischt',aux:'haben'},
 {inf:'rühren',en:'to stir',pt:'rührte',pp:'gerührt',aux:'haben'},
 {inf:'grillen',en:'to grill',pt:'grillte',pp:'gegrillt',aux:'haben'},
 {inf:'füllen',en:'to fill',pt:'füllte',pp:'gefüllt',aux:'haben'},
 {inf:'öffnen',en:'to open',du:'öffnest',er:'öffnet',pt:'öffnete',pp:'geöffnet',aux:'haben'},
 {inf:'schließen',en:'to close',du:'schließt',er:'schließt',pt:'schloss',pp:'geschlossen',aux:'haben'},
 {inf:'drücken',en:'to press / push',pt:'drückte',pp:'gedrückt',aux:'haben'},
 {inf:'ziehen',en:'to pull',pt:'zog',pp:'gezogen',aux:'haben'},
 {inf:'schieben',en:'to push / shove',pt:'schob',pp:'geschoben',aux:'haben'},
 {inf:'heben',en:'to lift',pt:'hob',pp:'gehoben',aux:'haben'},
 {inf:'werfen',en:'to throw',du:'wirfst',er:'wirft',pt:'warf',pp:'geworfen',aux:'haben'},
 {inf:'fangen',en:'to catch',du:'fängst',er:'fängt',pt:'fing',pp:'gefangen',aux:'haben'},
 {inf:'halten',en:'to hold / stop',du:'hältst',er:'hält',pt:'hielt',pp:'gehalten',aux:'haben'},
 {inf:'lassen',en:'to let / leave',du:'lässt',er:'lässt',pt:'ließ',pp:'gelassen',aux:'haben'},
 {inf:'rennen',en:'to run fast',pt:'rannte',pp:'gerannt',aux:'sein'},
 {inf:'springen',en:'to jump',pt:'sprang',pp:'gesprungen',aux:'sein'},
 {inf:'fallen',en:'to fall',du:'fällst',er:'fällt',pt:'fiel',pp:'gefallen',aux:'sein'},
 {inf:'steigen',en:'to climb / rise',pt:'stieg',pp:'gestiegen',aux:'sein'},
 {inf:'klettern',en:'to climb (up)',pt:'kletterte',pp:'geklettert',aux:'sein'},
 {inf:'wandern',en:'to hike',pt:'wanderte',pp:'gewandert',aux:'sein'},
 {inf:'reden',en:'to talk',pt:'redete',pp:'geredet',aux:'haben'},
 {inf:'rufen',en:'to call / shout',pt:'rief',pp:'gerufen',aux:'haben'},
 {inf:'schreien',en:'to scream',pt:'schrie',pp:'geschrien',aux:'haben'},
 {inf:'flüstern',en:'to whisper',pt:'flüsterte',pp:'geflüstert',aux:'haben'},
 {inf:'klingen',en:'to sound',pt:'klang',pp:'geklungen',aux:'haben'},
 {inf:'riechen',en:'to smell',pt:'roch',pp:'gerochen',aux:'haben'},
 {inf:'fühlen',en:'to feel',pt:'fühlte',pp:'gefühlt',aux:'haben'},
 {inf:'berühren',en:'to touch',pt:'berührte',pp:'berührt',aux:'haben'},
 {inf:'küssen',en:'to kiss',du:'küsst',er:'küsst',pt:'küsste',pp:'geküsst',aux:'haben'},
 {inf:'umarmen',en:'to hug',pt:'umarmte',pp:'umarmt',aux:'haben'},
 {inf:'lächeln',en:'to smile',pt:'lächelte',pp:'gelächelt',aux:'haben'},
 {inf:'träumen',en:'to dream',pt:'träumte',pp:'geträumt',aux:'haben'},
 {inf:'üben',en:'to practise',pt:'übte',pp:'geübt',aux:'haben'},
 {inf:'wiederholen',en:'to repeat',pt:'wiederholte',pp:'wiederholt',aux:'haben'},
 {inf:'kennen',en:'to know (someone)',pt:'kannte',pp:'gekannt',aux:'haben'},
 {inf:'nennen',en:'to name',pt:'nannte',pp:'genannt',aux:'haben'},
 {inf:'glauben',en:'to believe',pt:'glaubte',pp:'geglaubt',aux:'haben'},
 {inf:'hoffen',en:'to hope',pt:'hoffte',pp:'gehofft',aux:'haben'},
 {inf:'meinen',en:'to mean / think',pt:'meinte',pp:'gemeint',aux:'haben'},
 {inf:'vergleichen',en:'to compare',pt:'verglich',pp:'verglichen',aux:'haben'},
 {inf:'wählen',en:'to choose / vote',pt:'wählte',pp:'gewählt',aux:'haben'},
 {inf:'ändern',en:'to change',pt:'änderte',pp:'geändert',aux:'haben'},
 {inf:'wechseln',en:'to switch / exchange',pt:'wechselte',pp:'gewechselt',aux:'haben'},
 {inf:'sparen',en:'to save (money)',pt:'sparte',pp:'gespart',aux:'haben'},
 {inf:'verdienen',en:'to earn',pt:'verdiente',pp:'verdient',aux:'haben'},
 {inf:'verkaufen',en:'to sell',pt:'verkaufte',pp:'verkauft',aux:'haben'},
 {inf:'bestellen',en:'to order',pt:'bestellte',pp:'bestellt',aux:'haben'},
 {inf:'liefern',en:'to deliver',pt:'lieferte',pp:'geliefert',aux:'haben'},
 {inf:'schicken',en:'to send',pt:'schickte',pp:'geschickt',aux:'haben'},
 {inf:'erhalten',en:'to receive',du:'erhältst',er:'erhält',pt:'erhielt',pp:'erhalten',aux:'haben'},
 {inf:'schenken',en:'to give as a gift',pt:'schenkte',pp:'geschenkt',aux:'haben'},
 {inf:'malen',en:'to paint',pt:'malte',pp:'gemalt',aux:'haben'},
 {inf:'zeichnen',en:'to draw',du:'zeichnest',er:'zeichnet',pt:'zeichnete',pp:'gezeichnet',aux:'haben'},
 {inf:'basteln',en:'to do crafts',pt:'bastelte',pp:'gebastelt',aux:'haben'},
 {inf:'sammeln',en:'to collect',pt:'sammelte',pp:'gesammelt',aux:'haben'},
 {inf:'schießen',en:'to shoot',du:'schießt',er:'schießt',pt:'schoss',pp:'geschossen',aux:'haben'},
 {inf:'reiten',en:'to ride (horse)',pt:'ritt',pp:'geritten',aux:'sein'},
 {inf:'rudern',en:'to row',pt:'ruderte',pp:'gerudert',aux:'sein'},
 {inf:'joggen',en:'to jog',pt:'joggte',pp:'gejoggt',aux:'sein'},
 {inf:'landen',en:'to land',du:'landest',er:'landet',pt:'landete',pp:'gelandet',aux:'sein'},
 {inf:'parken',en:'to park',pt:'parkte',pp:'geparkt',aux:'haben'},
 {inf:'tanken',en:'to refuel',pt:'tankte',pp:'getankt',aux:'haben'},
 {inf:'mieten',en:'to rent',du:'mietest',er:'mietet',pt:'mietete',pp:'gemietet',aux:'haben'},
 {inf:'buchen',en:'to book',pt:'buchte',pp:'gebucht',aux:'haben'},
 {inf:'übernachten',en:'to stay overnight',du:'übernachtest',er:'übernachtet',pt:'übernachtete',pp:'übernachtet',aux:'haben'},
 {inf:'besichtigen',en:'to sightsee / view',pt:'besichtigte',pp:'besichtigt',aux:'haben'},
 {inf:'entdecken',en:'to discover',pt:'entdeckte',pp:'entdeckt',aux:'haben'},
 {inf:'erreichen',en:'to reach',pt:'erreichte',pp:'erreicht',aux:'haben'},
 {inf:'verpassen',en:'to miss (a train)',du:'verpasst',er:'verpasst',pt:'verpasste',pp:'verpasst',aux:'haben'},
 {inf:'renovieren',en:'to renovate',pt:'renovierte',pp:'renoviert',aux:'haben'},
 {inf:'trocknen',en:'to dry',du:'trocknest',er:'trocknet',pt:'trocknete',pp:'getrocknet',aux:'haben'},
 {inf:'bügeln',en:'to iron',pt:'bügelte',pp:'gebügelt',aux:'haben'},
 {inf:'nähen',en:'to sew',pt:'nähte',pp:'genäht',aux:'haben'},
 {inf:'benutzen',en:'to use',du:'benutzt',er:'benutzt',pt:'benutzte',pp:'benutzt',aux:'haben'},
 {inf:'drucken',en:'to print',pt:'druckte',pp:'gedruckt',aux:'haben'},
 {inf:'speichern',en:'to save (a file)',pt:'speicherte',pp:'gespeichert',aux:'haben'},
 {inf:'löschen',en:'to delete / extinguish',du:'löschst',er:'löscht',pt:'löschte',pp:'gelöscht',aux:'haben'},
 {inf:'laden',en:'to load / charge',du:'lädst',er:'lädt',pt:'lud',pp:'geladen',aux:'haben'},
 {inf:'tippen',en:'to type',pt:'tippte',pp:'getippt',aux:'haben'},
 {inf:'klicken',en:'to click',pt:'klickte',pp:'geklickt',aux:'haben'},
 {inf:'programmieren',en:'to program',pt:'programmierte',pp:'programmiert',aux:'haben'},
 {inf:'entwickeln',en:'to develop',pt:'entwickelte',pp:'entwickelt',aux:'haben'},
 {inf:'testen',en:'to test',du:'testest',er:'testet',pt:'testete',pp:'getestet',aux:'haben'},
 {inf:'messen',en:'to measure',du:'misst',er:'misst',pt:'maß',pp:'gemessen',aux:'haben'},
 {inf:'zählen',en:'to count',pt:'zählte',pp:'gezählt',aux:'haben'},
 {inf:'rechnen',en:'to calculate',du:'rechnest',er:'rechnet',pt:'rechnete',pp:'gerechnet',aux:'haben'},
 {inf:'teilen',en:'to share / divide',pt:'teilte',pp:'geteilt',aux:'haben'},
 {inf:'lösen',en:'to solve',du:'löst',er:'löst',pt:'löste',pp:'gelöst',aux:'haben'},
 {inf:'prüfen',en:'to check / test',pt:'prüfte',pp:'geprüft',aux:'haben'},
 {inf:'korrigieren',en:'to correct',pt:'korrigierte',pp:'korrigiert',aux:'haben'},
 {inf:'unterrichten',en:'to teach',du:'unterrichtest',er:'unterrichtet',pt:'unterrichtete',pp:'unterrichtet',aux:'haben'},
 {inf:'studieren',en:'to study (at university)',pt:'studierte',pp:'studiert',aux:'haben'},
 {inf:'forschen',en:'to research',du:'forschst',er:'forscht',pt:'forschte',pp:'geforscht',aux:'haben'},
 {inf:'erfinden',en:'to invent',du:'erfindest',er:'erfindet',pt:'erfand',pp:'erfunden',aux:'haben'},
 {inf:'merken',en:'to notice',pt:'merkte',pp:'gemerkt',aux:'haben'},
 {inf:'planen',en:'to plan',pt:'plante',pp:'geplant',aux:'haben'},
 {inf:'versprechen',en:'to promise',du:'versprichst',er:'verspricht',pt:'versprach',pp:'versprochen',aux:'haben'},
 {inf:'erlauben',en:'to allow',pt:'erlaubte',pp:'erlaubt',aux:'haben'},
 {inf:'verbieten',en:'to forbid',du:'verbietest',er:'verbietet',pt:'verbot',pp:'verboten',aux:'haben'},
 {inf:'zwingen',en:'to force',pt:'zwang',pp:'gezwungen',aux:'haben'},
 {inf:'bitten',en:'to ask (a favour)',du:'bittest',er:'bittet',pt:'bat',pp:'gebeten',aux:'haben'},
 {inf:'danken',en:'to thank',pt:'dankte',pp:'gedankt',aux:'haben'},
 {inf:'grüßen',en:'to greet',du:'grüßt',er:'grüßt',pt:'grüßte',pp:'gegrüßt',aux:'haben'},
 {inf:'begrüßen',en:'to welcome',du:'begrüßt',er:'begrüßt',pt:'begrüßte',pp:'begrüßt',aux:'haben'},
 {inf:'streiten',en:'to argue',du:'streitest',er:'streitet',pt:'stritt',pp:'gestritten',aux:'haben'},
 {inf:'kämpfen',en:'to fight',pt:'kämpfte',pp:'gekämpft',aux:'haben'},
 {inf:'schlagen',en:'to hit / beat',du:'schlägst',er:'schlägt',pt:'schlug',pp:'geschlagen',aux:'haben'},
 {inf:'schützen',en:'to protect',du:'schützt',er:'schützt',pt:'schützte',pp:'geschützt',aux:'haben'},
 {inf:'retten',en:'to rescue',du:'rettest',er:'rettet',pt:'rettete',pp:'gerettet',aux:'haben'},
 {inf:'unterstützen',en:'to support',du:'unterstützt',er:'unterstützt',pt:'unterstützte',pp:'unterstützt',aux:'haben'},
 {inf:'pflegen',en:'to care for',pt:'pflegte',pp:'gepflegt',aux:'haben'},
 {inf:'füttern',en:'to feed',pt:'fütterte',pp:'gefüttert',aux:'haben'},
 {inf:'jagen',en:'to hunt',pt:'jagte',pp:'gejagt',aux:'haben'},
 {inf:'pflanzen',en:'to plant',du:'pflanzt',er:'pflanzt',pt:'pflanzte',pp:'gepflanzt',aux:'haben'},
 {inf:'wachsen',en:'to grow',du:'wächst',er:'wächst',pt:'wuchs',pp:'gewachsen',aux:'sein'},
 {inf:'blühen',en:'to bloom',pt:'blühte',pp:'geblüht',aux:'haben'},
 {inf:'sterben',en:'to die',du:'stirbst',er:'stirbt',pt:'starb',pp:'gestorben',aux:'sein'},
 {inf:'atmen',en:'to breathe',du:'atmest',er:'atmet',pt:'atmete',pp:'geatmet',aux:'haben'},
 {inf:'husten',en:'to cough',du:'hustest',er:'hustet',pt:'hustete',pp:'gehustet',aux:'haben'},
 {inf:'niesen',en:'to sneeze',du:'niest',er:'niest',pt:'nieste',pp:'geniest',aux:'haben'},
 {inf:'bluten',en:'to bleed',du:'blutest',er:'blutet',pt:'blutete',pp:'geblutet',aux:'haben'},
 {inf:'heilen',en:'to heal',pt:'heilte',pp:'geheilt',aux:'haben'},
 {inf:'untersuchen',en:'to examine',pt:'untersuchte',pp:'untersucht',aux:'haben'},
 {inf:'behandeln',en:'to treat',pt:'behandelte',pp:'behandelt',aux:'haben'},
 {inf:'operieren',en:'to operate',pt:'operierte',pp:'operiert',aux:'haben'},
 {inf:'wiegen',en:'to weigh',pt:'wog',pp:'gewogen',aux:'haben'},
 {inf:'scheinen',en:'to shine / seem',pt:'schien',pp:'geschienen',aux:'haben'},
 {inf:'frieren',en:'to freeze / be cold',pt:'fror',pp:'gefroren',aux:'haben'},
 {inf:'schwitzen',en:'to sweat',du:'schwitzt',er:'schwitzt',pt:'schwitzte',pp:'geschwitzt',aux:'haben'},
 {inf:'brennen',en:'to burn',pt:'brannte',pp:'gebrannt',aux:'haben'},
 {inf:'leuchten',en:'to glow / shine',du:'leuchtest',er:'leuchtet',pt:'leuchtete',pp:'geleuchtet',aux:'haben'},
 {inf:'klingeln',en:'to ring (bell)',pt:'klingelte',pp:'geklingelt',aux:'haben'},
 {inf:'klopfen',en:'to knock',pt:'klopfte',pp:'geklopft',aux:'haben'},
 {inf:'warnen',en:'to warn',pt:'warnte',pp:'gewarnt',aux:'haben'},
 {inf:'melden',en:'to report / register',du:'meldest',er:'meldet',pt:'meldete',pp:'gemeldet',aux:'haben'},
 {inf:'berichten',en:'to report (news)',du:'berichtest',er:'berichtet',pt:'berichtete',pp:'berichtet',aux:'haben'},
 {inf:'beschreiben',en:'to describe',pt:'beschrieb',pp:'beschrieben',aux:'haben'},
 {inf:'übersetzen',en:'to translate',du:'übersetzt',er:'übersetzt',pt:'übersetzte',pp:'übersetzt',aux:'haben'},
 {inf:'bedeuten',en:'to mean',du:'bedeutest',er:'bedeutet',pt:'bedeutete',pp:'bedeutet',aux:'haben'},
 {inf:'buchstabieren',en:'to spell',pt:'buchstabierte',pp:'buchstabiert',aux:'haben'},
 {inf:'antworten',en:'to answer',du:'antwortest',er:'antwortet',pt:'antwortete',pp:'geantwortet',aux:'haben'},
 {inf:'schweigen',en:'to be silent',pt:'schwieg',pp:'geschwiegen',aux:'haben'},
 {inf:'folgen',en:'to follow',pt:'folgte',pp:'gefolgt',aux:'sein'},
 {inf:'führen',en:'to lead',pt:'führte',pp:'geführt',aux:'haben'},
 {inf:'leiten',en:'to manage / direct',du:'leitest',er:'leitet',pt:'leitete',pp:'geleitet',aux:'haben'},
 {inf:'kündigen',en:'to quit / cancel',pt:'kündigte',pp:'gekündigt',aux:'haben'},
 {inf:'produzieren',en:'to produce',pt:'produzierte',pp:'produziert',aux:'haben'},
 {inf:'verbrauchen',en:'to consume',pt:'verbrauchte',pp:'verbraucht',aux:'haben'},
 {inf:'sortieren',en:'to sort',pt:'sortierte',pp:'sortiert',aux:'haben'},
 {inf:'ordnen',en:'to arrange',du:'ordnest',er:'ordnet',pt:'ordnete',pp:'geordnet',aux:'haben'},
 {inf:'decken',en:'to cover / set (table)',pt:'deckte',pp:'gedeckt',aux:'haben'},
 {inf:'servieren',en:'to serve',pt:'servierte',pp:'serviert',aux:'haben'},
 {inf:'genießen',en:'to enjoy',du:'genießt',er:'genießt',pt:'genoss',pp:'genossen',aux:'haben'},
 {inf:'verwenden',en:'to use / apply',du:'verwendest',er:'verwendet',pt:'verwendete',pp:'verwendet',aux:'haben'},
 {inf:'gefallen',en:'to please',du:'gefällst',er:'gefällt',pt:'gefiel',pp:'gefallen',aux:'haben'},
 {inf:'gehören',en:'to belong',pt:'gehörte',pp:'gehört',aux:'haben'},
 {inf:'passen',en:'to fit',du:'passt',er:'passt',pt:'passte',pp:'gepasst',aux:'haben'},
 {inf:'passieren',en:'to happen',pt:'passierte',pp:'passiert',aux:'sein'},
 {inf:'existieren',en:'to exist',pt:'existierte',pp:'existiert',aux:'haben'},
 {inf:'telefonieren',en:'to phone',pt:'telefonierte',pp:'telefoniert',aux:'haben'},
 {inf:'fotografieren',en:'to photograph',pt:'fotografierte',pp:'fotografiert',aux:'haben'},
 {inf:'reparieren',en:'to repair',pt:'reparierte',pp:'repariert',aux:'haben'},
 {inf:'funktionieren',en:'to function / work',pt:'funktionierte',pp:'funktioniert',aux:'haben'},
 {inf:'organisieren',en:'to organise',pt:'organisierte',pp:'organisiert',aux:'haben'},
 {inf:'informieren',en:'to inform',pt:'informierte',pp:'informiert',aux:'haben'},
 {inf:'reservieren',en:'to reserve',pt:'reservierte',pp:'reserviert',aux:'haben'},
 {inf:'diskutieren',en:'to discuss',pt:'diskutierte',pp:'diskutiert',aux:'haben'},
 {inf:'gratulieren',en:'to congratulate',pt:'gratulierte',pp:'gratuliert',aux:'haben'},
 {inf:'akzeptieren',en:'to accept',pt:'akzeptierte',pp:'akzeptiert',aux:'haben'},
 {inf:'reagieren',en:'to react',pt:'reagierte',pp:'reagiert',aux:'haben'},
 {inf:'trainieren',en:'to train',pt:'trainierte',pp:'trainiert',aux:'haben'},
 {inf:'kopieren',en:'to copy',pt:'kopierte',pp:'kopiert',aux:'haben'},
 {inf:'notieren',en:'to note down',pt:'notierte',pp:'notiert',aux:'haben'},
 {inf:'kontrollieren',en:'to check / control',pt:'kontrollierte',pp:'kontrolliert',aux:'haben'}
);

/* ===== adjectives ===== */
EXTRA_VOCAB.adjs.push(
 {de:'bekannt',en:'well-known',opp:'unbekannt'},{de:'unbekannt',en:'unknown',opp:'bekannt'},
 {de:'berühmt',en:'famous',opp:null},{de:'beliebt',en:'popular',opp:null},
 {de:'modern',en:'modern',opp:'altmodisch'},{de:'altmodisch',en:'old-fashioned',opp:'modern'},
 {de:'praktisch',en:'practical',opp:null},{de:'bequem',en:'comfortable',opp:'unbequem'},
 {de:'unbequem',en:'uncomfortable',opp:'bequem'},{de:'eng',en:'tight / narrow',opp:'weit'},
 {de:'breit',en:'wide',opp:'schmal'},{de:'schmal',en:'narrow',opp:'breit'},
 {de:'tief',en:'deep',opp:'flach'},{de:'flach',en:'flat / shallow',opp:'tief'},
 {de:'hoch',en:'high',opp:'niedrig'},{de:'niedrig',en:'low',opp:'hoch'},
 {de:'dick',en:'thick / fat',opp:'dünn'},{de:'dünn',en:'thin',opp:'dick'},
 {de:'schwer',en:'heavy / difficult',opp:'leicht'},{de:'leicht',en:'light / easy',opp:'schwer'},
 {de:'hart',en:'hard',opp:'weich'},{de:'weich',en:'soft',opp:'hart'},
 {de:'glatt',en:'smooth',opp:'rau'},{de:'rau',en:'rough',opp:'glatt'},
 {de:'scharf',en:'spicy / sharp',opp:'mild'},{de:'mild',en:'mild',opp:'scharf'},
 {de:'frisch',en:'fresh',opp:null},{de:'roh',en:'raw',opp:null},
 {de:'lecker',en:'tasty',opp:null},{de:'bitter',en:'bitter',opp:null},
 {de:'salzig',en:'salty',opp:null},{de:'saftig',en:'juicy',opp:null},
 {de:'schmutzig',en:'dirty',opp:'sauber'},{de:'ordentlich',en:'tidy',opp:'unordentlich'},
 {de:'unordentlich',en:'messy',opp:'ordentlich'},{de:'pünktlich',en:'punctual',opp:null},
 {de:'ehrlich',en:'honest',opp:null},{de:'klug',en:'clever',opp:'dumm'},
 {de:'dumm',en:'stupid',opp:'klug'},{de:'weise',en:'wise',opp:null},
 {de:'mutig',en:'brave',opp:'feige'},{de:'feige',en:'cowardly',opp:'mutig'},
 {de:'stolz',en:'proud',opp:null},{de:'schüchtern',en:'shy',opp:null},
 {de:'geduldig',en:'patient',opp:'ungeduldig'},{de:'ungeduldig',en:'impatient',opp:'geduldig'},
 {de:'zufrieden',en:'satisfied',opp:null},{de:'dankbar',en:'grateful',opp:null},
 {de:'wütend',en:'furious',opp:null},{de:'einsam',en:'lonely',opp:null},
 {de:'fröhlich',en:'cheerful',opp:null},{de:'ernst',en:'serious',opp:null},
 {de:'streng',en:'strict',opp:null},{de:'sanft',en:'gentle',opp:null},
 {de:'treu',en:'loyal',opp:null},{de:'gerecht',en:'just / fair',opp:'ungerecht'},
 {de:'ungerecht',en:'unjust',opp:'gerecht'},{de:'gemein',en:'mean',opp:'nett'},
 {de:'nett',en:'nice',opp:'gemein'},{de:'sympathisch',en:'likeable',opp:null},
 {de:'hübsch',en:'pretty',opp:'hässlich'},{de:'hässlich',en:'ugly',opp:'hübsch'},
 {de:'elegant',en:'elegant',opp:null},{de:'sportlich',en:'sporty',opp:null},
 {de:'kräftig',en:'strong / powerful',opp:null},{de:'fit',en:'fit',opp:null},
 {de:'wach',en:'awake',opp:'müde'},{de:'satt',en:'full (after eating)',opp:'hungrig'},
 {de:'verletzt',en:'injured',opp:null},{de:'berufstätig',en:'employed',opp:null}
);

/* ===== phrases ===== */
EXTRA_VOCAB.phrases.push(
 {de:'Wie bitte?',en:'Pardon? / What did you say?'},
 {de:'Es ist höchste Zeit',en:'It is high time'},
 {de:'Mir ist langweilig',en:'I am bored'},
 {de:'Ich habe keine Lust',en:'I do not feel like it'},
 {de:'Das lohnt sich',en:'It is worth it'},
 {de:'Es kommt darauf an',en:'It depends'},
 {de:'Ich bin dafür',en:'I am in favour'},
 {de:'Ich bin dagegen',en:'I am against it'},
 {de:'Meiner Meinung nach',en:'In my opinion'},
 {de:'Ich bin mir sicher',en:'I am sure'},
 {de:'Ich bin mir nicht sicher',en:'I am not sure'},
 {de:'Das stimmt',en:'That is right'},
 {de:'Das stimmt nicht',en:'That is not right'},
 {de:'Du hast recht',en:'You are right'},
 {de:'Ich habe mich verlaufen',en:'I got lost'},
 {de:'Ich habe den Zug verpasst',en:'I missed the train'},
 {de:'Wann fährt der nächste Zug?',en:'When does the next train leave?'},
 {de:'Einmal nach Berlin, bitte',en:'One ticket to Berlin, please'},
 {de:'Ist dieser Platz frei?',en:'Is this seat free?'},
 {de:'Wie komme ich zum Bahnhof?',en:'How do I get to the station?'},
 {de:'Immer geradeaus',en:'Straight ahead'},
 {de:'Erste Straße links',en:'First street on the left'},
 {de:'Zweite Straße rechts',en:'Second street on the right'},
 {de:'Ich möchte einen Tisch reservieren',en:'I would like to reserve a table'},
 {de:'Haben Sie noch ein Zimmer frei?',en:'Do you still have a room available?'},
 {de:'Wann gibt es Frühstück?',en:'When is breakfast served?'},
 {de:'Können Sie mir das zeigen?',en:'Can you show me that?'},
 {de:'Ich schaue mich nur um',en:'I am just looking around'},
 {de:'Kann ich mit Karte zahlen?',en:'Can I pay by card?'},
 {de:'Nur Bargeld, bitte',en:'Cash only, please'},
 {de:'Das passt mir gut',en:'That fits me well'},
 {de:'Das ist zu groß',en:'That is too big'},
 {de:'Das ist zu klein',en:'That is too small'},
 {de:'Ich nehme es',en:'I will take it'},
 {de:'Alles Gute zum Geburtstag',en:'Happy birthday'},
 {de:'Frohe Weihnachten',en:'Merry Christmas'},
 {de:'Frohes neues Jahr',en:'Happy New Year'},
 {de:'Schöne Ferien',en:'Have a nice holiday'},
 {de:'Gute Reise',en:'Have a good trip'},
 {de:'Willkommen in Deutschland',en:'Welcome to Germany'},
 {de:'Bis bald',en:'See you soon'},
 {de:'Bis gleich',en:'See you in a moment'},
 {de:'Keine Ahnung',en:'No idea'},
 {de:'Zum Wohl',en:'To your health'},
 {de:'Es freut mich, Sie kennenzulernen',en:'Pleased to meet you'}
);

/* ===== picture emoji for new nouns ===== */
Object.assign(EXTRA_VOCAB.imgs,{
 Sonnenblume:'🌻',Elefant:'🐘',Tiger:'🐯',Giraffe:'🦒',Kamel:'🐫',Wolf:'🐺',Fuchs:'🦊',
 Hase:'🐇',Kaninchen:'🐰',Eichhörnchen:'🐿️',Igel:'🦔',Hirsch:'🦌',Ziege:'🐐',Esel:'🫏',
 Huhn:'🐔',Hahn:'🐓',Ente:'🦆',Gans:'🪿',Schwan:'🦢',Eule:'🦉',Adler:'🦅',Taube:'🕊️',
 Papagei:'🦜',Pinguin:'🐧',Delfin:'🐬',Wal:'🐋',Hai:'🦈',Frosch:'🐸',Schlange:'🐍',
 Schildkröte:'🐢',Biene:'🐝',Ameise:'🐜',Fliege:'🪰',Mücke:'🦟',Schmetterling:'🦋',
 Spinne:'🕷️',Käfer:'🪲',Schnecke:'🐌',Wurm:'🪱',Feder:'🪶',Nest:'🪹',
 Erdbeere:'🍓',Kirsche:'🍒',Birne:'🍐',Pfirsich:'🍑',Traube:'🍇',Melone:'🍉',Ananas:'🍍',
 Zitrone:'🍋',Erdnuss:'🥜',Zwiebel:'🧅',Knoblauch:'🧄',Paprika:'🫑',Gurke:'🥒',Karotte:'🥕',
 Pilz:'🍄',Brötchen:'🥐',Keks:'🍪',Bonbon:'🍬',Pizza:'🍕',Wurst:'🌭',Saft:'🧃',
 Flasche:'🍾',Teller:'🍽️',Messer:'🔪',Löffel:'🥄',Topf:'🍲',
 Hose:'👖',Rock:'👗',Pullover:'🧥',Jacke:'🧥',Mantel:'🧥',Anzug:'🤵',Krawatte:'👔',
 Socke:'🧦',Stiefel:'🥾',Mütze:'🧢',Hut:'🎩',Schal:'🧣',Handschuh:'🧤',Ring:'💍',
 Regenschirm:'☂️',Koffer:'🧳',Rucksack:'🎒',
 Wolke:'☁️',Blitz:'⚡',Regenbogen:'🌈',Feuer:'🔥',Welle:'🌊',Strand:'🏖️',Zelt:'⛺',
 Vulkan:'🌋',Weltkugel:'🌍',Welt:'🌍',Rose:'🌹',Kerze:'🕯️',Glocke:'🔔',Fahne:'🚩',
 Krone:'👑',Schwert:'⚔️',Diamant:'💎',Ballon:'🎈',Drachen:'🪁',Geschenk:'🎁',
 Gitarre:'🎸',Klavier:'🎹',Geige:'🎻',Trommel:'🥁',Fußball:'⚽',Basketball:'🏀',
 Medaille:'🏅',Schach:'♟️',Würfel:'🎲',Puppe:'🪆',
 Motorrad:'🏍️',Lastwagen:'🚚',Taxi:'🚕',Hubschrauber:'🚁',Boot:'🛶','U-Bahn':'🚇',
 Straßenbahn:'🚋',Bett:'🛏️',Dusche:'🚿',Badewanne:'🛁',Seife:'🧼',Zahnbürste:'🪥',
 Besen:'🧹',Mülleimer:'🗑️',Werkzeug:'🛠️',Hammer:'🔨',Kamera:'📷',Fernseher:'📺',
 Radio:'📻',Kopfhörer:'🎧',Drucker:'🖨️',Tastatur:'⌨️',Bleistift:'✏️',Heft:'📓',
 Umschlag:'✉️',Briefmarke:'📮',Münze:'🪙',Kreditkarte:'💳',Paket:'📦',Museum:'🏛️',
 Theater:'🎭',Zoo:'🦁',Turm:'🗼',Schloss:'🏰',Rathaus:'🏛️'
});
EXTRA_VOCAB.pics.push('Elefant','Tiger','Giraffe','Wolf','Fuchs','Igel','Ente','Eule','Adler','Papagei',
 'Pinguin','Delfin','Wal','Hai','Frosch','Schlange','Schildkröte','Biene','Schmetterling','Spinne',
 'Schnecke','Erdbeere','Kirsche','Birne','Traube','Melone','Ananas','Zitrone','Zwiebel','Karotte',
 'Pilz','Pizza','Hose','Socke','Stiefel','Mütze','Schal','Handschuh','Ring','Regenschirm','Koffer',
 'Rucksack','Wolke','Regenbogen','Feuer','Zelt','Rose','Kerze','Glocke','Krone','Diamant','Ballon',
 'Gitarre','Klavier','Geige','Trommel','Fußball','Basketball','Würfel','Motorrad','Taxi','Hubschrauber',
 'Bett','Dusche','Badewanne','Zahnbürste','Besen','Hammer','Kamera','Fernseher','Kopfhörer','Bleistift',
 'Münze','Paket','Theater','Turm');

/* top-up */
EXTRA_VOCAB.nouns.push(
 {de:'Gebäude',en:'building',g:'n',pl:'Gebäude'},{de:'Bahnsteig',en:'railway platform',g:'m',pl:'Bahnsteige'},
 {de:'Landschaft',en:'landscape',g:'f',pl:'Landschaften'},{de:'Stimmung',en:'mood',g:'f',pl:'Stimmungen'},
 {de:'Gastgeber',en:'host',g:'m',pl:'Gastgeber'},{de:'Erlebnis',en:'experience (event)',g:'n',pl:'Erlebnisse'},
 {de:'Gewohnheit',en:'habit',g:'f',pl:'Gewohnheiten'},{de:'Verhalten',en:'behaviour',g:'n',pl:null},
 {de:'Umgebung',en:'surroundings',g:'f',pl:'Umgebungen'},{de:'Gelegenheit',en:'opportunity',g:'f',pl:'Gelegenheiten'}
);
